import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { LocalStore } from '@learnbridge/local-storage';
import { startRuntime } from '../apps/local-runtime/src/server.mjs';
import { createCloudBundle, validateCloudBundle, CLOUD_PROVIDERS } from '../apps/local-runtime/src/cloud-onboarding.mjs';
import { createHostedEmailOnboarding, EMAIL_TOOL_CONTRACT as C } from '../apps/web/src/lib/server/email-onboarding-service.mjs';
const OWNER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',BODY='SYNTHETIC_PRIVATE_EMAIL_IMPORT\n<script>doNotExecute()</script>',scope={folder:'INBOX',start_date:'2026-09-01',end_date:'2026-09-30',subject_phrase:'Lecture'};
async function transfer(){const meta={messageId:'19b11732c1b578f0',threadId:'19b11732c1b57000',subject:'Lecture reminder',sender:'course@example.test',to:'student@example.test',messageTimestamp:'2026-09-15T14:00:00Z',labelIds:['INBOX']},service=createHostedEmailOnboarding({userId:OWNER,origin:'https://learnbridge.example',secret:'synthetic-private-signing-only',transport:{listAccounts:async()=>({items:[{id:'ca_gmail',owner_id:OWNER,provider:'gmail',shared:false,status:'ACTIVE',configured:true}]}),schemas:async()=>[{slug:C.search,version:C.version,input_fields:C.searchFields},{slug:C.read,version:C.version,input_fields:C.readFields}],execute:async(_owner,_account,slug)=>slug===C.search?{messages:[meta],nextPageToken:''}:{...meta,payload:{mimeType:'text/plain',headers:[{name:'Date',value:'Tue, 15 Sep 2026 14:00:00 +0000'}],body:{data:Buffer.from(BODY).toString('base64url')}}}}});const found=await service.search({account_id:'ca_gmail',scope}),preview=await service.preview({account_id:'ca_gmail',selection_tokens:[found.items[0].selection_token],academic_policy:'graded_restricted'});return (await service.export({preview_token:preview.preview_token,review_hash:preview.review_hash,confirm:true})).bundle}
async function fixture(t){const parent=mkdtempSync(join(tmpdir(),'learnbridge-email-local-')),root=join(parent,'workspace');let runtime;
 t.after(async()=>{await runtime?.close();rmSync(parent,{recursive:true,force:true})});
 async function restart(dataRoot=root){await runtime?.close();runtime=await startRuntime({dataRoot,port:0,hostAdapter:{enabled:false}});const paired=await fetch(runtime.origin+'/api/local/v1/pair',{method:'POST',headers:{Origin:runtime.origin,'Content-Type':'application/json'},body:JSON.stringify({code:runtime.createPairingCode()})}),session=await paired.json(),cookie=paired.headers.get('set-cookie').split(';')[0],origin=runtime.origin;
  return async(path,body,method=body===undefined?'GET':'POST',more={})=>{const response=await fetch(origin+'/api/local/v1'+path,{method,headers:{Origin:origin,Cookie:cookie,'X-LearnBridge-Nonce':session.nonce,...(body===undefined?{}:{'Content-Type':'application/json'}),...more},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,data:await response.json()}};
 }
 return {parent,root,restart,close:()=>runtime.close(),call:await restart()};
}
async function preview(call,bundle){const r=await call('/cloud-onboarding/preview',{bundle,academic_policy:'unrestricted'});assert.equal(r.status,200,JSON.stringify(r.data));return r.data}
const save=(call,picked)=>call('/cloud-onboarding/imports',{preview_id:picked.preview_id,review_hash:picked.preview.review_hash,confirm_owner:true});
test('ELOCAL01 actual hosted export → paired local preview/import/readback preserves private source provenance and grants no model/task/profile access',async t=>{
 const bundle=await transfer(),f=await fixture(t),picked=await preview(f.call,bundle);assert.equal(picked.preview.academic_policy,'graded_restricted');assert.equal(picked.preview.owner_verification,'bundle_reported_needs_student_confirmation');assert.equal((await f.call('/documents')).data.items.length,0);
 assert.equal((await f.call('/cloud-onboarding/imports',{preview_id:picked.preview_id,review_hash:picked.preview.review_hash,confirm_owner:false})).status,403);
 const saved=await save(f.call,picked);assert.equal(saved.status,201);assert.equal((await save(f.call,picked)).status,200);const item=saved.data.item;assert.equal(item.provider,'gmail');assert.equal(item.owner_verification,'student_confirmed_bundle_reported');assert.equal(item.source_freshness,'not_checked');assert.deepEqual(item.records[0].source_metadata,bundle.records[0].source_metadata);
 const note=(await f.call('/documents/'+item.notes[0].id)).data;assert(note.content.startsWith(BODY));assert.match(note.content,/From \(provider reported\): course@example.test/);assert.match(note.content,/Provider timestamp \(meaning unverified\): 2026-09-15T14:00:00Z/);assert.match(note.content,/Received time: not reported/);assert.equal(note.document.academic_policy,'graded_restricted');assert.equal(createHash('sha256').update(note.content).digest('hex'),item.notes[0].sha256);
 assert.equal((await f.call('/documents')).data.items.length,1);for(const path of ['/tasks','/profile','/agent-grants'])assert.equal((await f.call(path)).data.items.length,0);
 const receipts=(await f.call('/cloud-onboarding/imports')).data;assert.equal(JSON.stringify(receipts).includes(BODY),false);assert.equal(receipts.items[0].records[0].source_metadata.from,'course@example.test');
});
test('ELOCAL02 v2 email validation rejects altered provenance/policy/hashes and does not widen v1 acquisition providers',async t=>{
 const bundle=await transfer();assert.deepEqual(CLOUD_PROVIDERS,['googledocs','notion']);assert.deepEqual(validateCloudBundle(bundle),bundle);
 for(const alter of [value=>{value.schema_version=1},value=>{value.provider='notion'},value=>{value.records[0].source_metadata.message_id='19b11732c1b578ff'},value=>{value.records[0].source_metadata.received_at='2026-09-15T14:00:00.000Z'},value=>{value.records[0].source_metadata.sent_at='2026-09-16T14:00:00.000Z'},value=>{value.records[0].source_metadata.selected_scope.folder='ALL'},value=>{value.records[0].source_metadata.token='private'},value=>{value.records[0].url='https://mail.google.com/private'},value=>{value.records[0].text='Edited body'}]){const changed=structuredClone(bundle);alter(changed);assert.throws(()=>validateCloudBundle(changed))}
 const f=await fixture(t),picked=await preview(f.call,bundle),imported=await save(f.call,picked),pin=imported.data.item.notes[0];assert.equal((await f.call('/documents/'+pin.id,{expected_revision:pin.revision,content:'Student edits retained'},'PATCH')).status,200);assert.equal((await save(f.call,picked)).status,409);assert.equal((await f.call('/cloud-onboarding/preview',{bundle,academic_policy:'learning_support'})).status,409);assert.equal((await f.call('/documents/'+pin.id)).data.content,'Student edits retained');
 const old=createCloudBundle({format:'learnbridge-selected-cloud-export',schema_version:1,origin:'https://learnbridge.example',owner:{student_id:OWNER,verification:'supabase_session_at_fetch'},provider:'googledocs',account_id:'ca_docs',academic_policy:'learning_support',retrieved_at:new Date().toISOString(),records:[{id:'synthetic_document_1',title:'Old compatible transfer',url:'https://docs.google.com/document/d/synthetic_document_1/edit',modified_at:null,text:'Preserved v1 plaintext',sha256:createHash('sha256').update('Preserved v1 plaintext').digest('hex'),coverage:'partial_text',limitations:['Original visuals not checked.']}],limitations:['Selected snapshot only.']});assert.equal((await save(f.call,await preview(f.call,old))).status,201);assert.equal((await f.call('/documents')).data.items.length,2);
});
test('ELOCAL03 email notes and exact provenance receipts survive restart and fresh backup restore; review sessions do not',async t=>{
 const f=await fixture(t),picked=await preview(f.call,await transfer()),saved=await save(f.call,picked),item=saved.data.item,content=(await f.call('/documents/'+item.notes[0].id)).data;
 let call=await f.restart();assert.equal((await save(call,picked)).status,403);assert.deepEqual((await call('/cloud-onboarding/imports/'+item.id)).data.item,item);
 await f.close();const store=LocalStore.open({root:f.root});try{await store.backup(join(f.parent,'backup'))}finally{store.close()};const restored=join(f.parent,'restored');await LocalStore.restore({backupRoot:join(f.parent,'backup'),root:restored});call=await f.restart(restored);
 assert.deepEqual((await call('/cloud-onboarding/imports/'+item.id)).data.item,item);assert.deepEqual((await call('/documents/'+item.notes[0].id)).data,content);assert.equal((await call('/agent-grants')).data.items.length,0);
});
