import test from 'node:test';
import assert from 'node:assert/strict';
import { mountLeetCodeUI } from '../apps/local/public/leetcode.js';

// Executes the shipped handlers. Physical voice, authenticated LeetCode and
// actual model behavior require separate account/device checks.
class Node {
  constructor(tag, cls = '', text = '') { this.tagName = tag; this.className = cls; this.text = text; this.children = []; this.listeners = new Map(); this.disabled = false; this.hidden = false; this._value = ''; this.attributes = new Map(); this.classList = { toggle: () => {} }; }
  append(...nodes) { this.children.push(...nodes); }
  replaceChildren(...nodes) { this.children = nodes; this.text = ''; this._value = ''; }
  addEventListener(name, fn) { this.listeners.set(name, [...(this.listeners.get(name) || []), fn]); }
  dispatchEvent(event) { fire(this, event.type); }
  setAttribute(name, value) { this.attributes.set(name, value); }
  get options() { return this.children; }
  get value() { return this._value || (this.tagName === 'select' ? this.children[0]?.value || '' : ''); }
  set value(value) { this._value = String(value); }
  get textContent() { return this.text + this.children.map(node => node.textContent).join(''); }
  set textContent(value) { this.text = String(value); this.children = []; }
  scrollIntoView() {}
}
const walk = root => [root, ...root.children.flatMap(walk)];
const fire = (node, type = 'click') => { for (const handler of node.listeners.get(type) || []) handler({ preventDefault() {} }); };
const deferred = () => { let resolve; const promise = new Promise(done => { resolve = done; }); return { promise, resolve }; };
const hash = 'a'.repeat(64), snapshot = { id: 'saved-history', revision: 1, sha256: hash, title: 'student', data: { username: 'student', observed_at: '2026-10-05T12:00:00Z', coverage: { scope: 'bounded_private_history' }, attempts: [{ id: '111', slug: 'two-sum', title: 'Two Sum', status: 'Wrong Answer', language: 'python3', timestamp: 1791200000 }, { id: '112', slug: 'two-sum', title: 'Two Sum', status: 'Accepted', language: 'python3', timestamp: 1791201000 }] } };
const problem = { id: 'problem-1', revision: 1, sha256: hash, title: 'Two Sum', data: { title: 'Two Sum', slug: 'two-sum', content: 'Return the two indices.', difficulty: 'Easy', tags: ['Array'], code_snippets: [{ lang: 'Python3', lang_slug: 'python3', code: '# starter' }], url: 'https://leetcode.com/problems/two-sum/' } };
function session(id = 'practice-1') { return { id, revision: 1, title: 'Coding practice: Two Sum', created_at: '2026-10-05T12:00:00Z', elapsed_ms: 0, data: { context_hash: hash, context_note: null, language: 'python3', mode: 'practice', state: 'ready', coaching: [], pending: null, elapsed_ms: 0, context: { problem: { ...problem.data, starter: problem.data.code_snippets[0] } } }, checkpoints: [] }; }
function harness(t, options = {}) {
  const root = new Node('main'), calls = [], jobs = [], confirmations = [], data = { connection: options.connection || { state: 'private', username: 'student' }, browser: options.browser || { state: 'closed', profile_retained: false, owner: true, capability: { state: 'available', detail: 'Dedicated local Chrome is available.' } }, snapshots: [structuredClone(snapshot)], problems: [structuredClone(problem)], analytics: { attempt_count: 2, distinct_problems: 1, accepted_attempts: 1, nonaccepted_attempts: 1, recommendations: [{ title: 'Revisit before memorizing', reason: 'Two observed attempts on the same problem include a failed outcome.', evidence_ids: ['111', '112'] }] } }, sessions = options.sessions || [session()], grants = options.grants || [];
  let recognition, aborts = 0; const globals = new Map(['SpeechRecognition', 'speechSynthesis'].map(name => [name, Object.getOwnPropertyDescriptor(globalThis, name)]));
  Object.defineProperty(globalThis, 'SpeechRecognition', { configurable: true, value: class { constructor() { recognition = this; } start() {} abort() { aborts++; this.onend?.(); } stop() { this.onend?.(); } } });
  Object.defineProperty(globalThis, 'speechSynthesis', { configurable: true, value: { cancel() {}, speak() {} } });
  const ui = mountLeetCodeUI({ root, element: (tag, cls, text) => new Node(tag, cls, text), request: async (path, extra = {}) => {
    calls.push({ path, ...structuredClone(extra) }); const override = options.handle?.(path, extra); if (override !== undefined) return await override;
    if (path === '/leetcode/state') return structuredClone(data);
    if (path === '/coding-practice/state') return { sessions: structuredClone(sessions), problems: structuredClone(data.problems), capability: { detail: 'Official host ready.' } };
    if (path === '/agent-grants' && !extra.method) return { items: structuredClone(grants) };
    if (path === '/leetcode/connect') { data.connection = { state: extra.body.session ? 'private' : 'public', username: extra.body.username }; return { connection: data.connection }; }
    if (path === '/leetcode/browser/start') { data.browser.state = 'open'; data.browser.profile_retained = true; return { browser: data.browser }; }
    if (path === '/leetcode/browser/check') { data.connection = { state: 'private', username: extra.body.username }; return { connection: data.connection }; }
    if (path === '/leetcode/browser/forget') { data.browser.state = 'closed'; data.browser.profile_retained = false; data.connection = { state: 'disconnected' }; return { browser: data.browser }; }
    if (path === '/leetcode/disconnect') { data.connection = { state: 'disconnected' }; return {}; }
    if (path === '/leetcode/sync') return { item: data.snapshots[0] };
    if (path === '/leetcode/snapshots/saved-history/export-context') return { item: { document: { id: 'history-note', title: 'Exact observed history' }, content: 'ONLY SELECTED HISTORY, WITHOUT SOURCE CODE OR COOKIE', sha256: hash, sharing: 'not_granted' } };
    if (path.startsWith('/leetcode/submissions/') || path.startsWith('/leetcode/saved-submissions/')) return { item: { id: 'submission-1', revision: 1, sha256: hash, data: { title: 'Two Sum', slug: 'two-sum', code: 'MY PRIVATE SUBMITTED CODE', language: 'python3', username: 'student', runtime: '10 ms', memory: '12 MB' } } };
    if (path === '/leetcode/problems') return { item: data.problems[0] };
    if (path === '/coding-practice/sessions') { const created = session(`practice-${sessions.length + 1}`); sessions.push(created); return { item: structuredClone(created) }; }
    if (path === '/agent-grants' && extra.method === 'POST') { const grant = { id: `grant-${grants.length + 1}`, destination: 'codex', state: 'active', expires_at: new Date(Date.now() + 300000).toISOString(), pins: { documents: extra.body.expected_records.documents, tasks: [], source_entries: [] } }; grants.push(grant); return { item: grant }; }
    const match = /^\/coding-practice\/sessions\/([^/]+)(?:\/(checkpoint|import-submission|export-context|preview-run|run|transition))?$/.exec(path);
    if (match) { const record = sessions.find(row => row.id === match[1]); assert(record); if (!match[2]) return { item: structuredClone(record) };
      if (match[2] === 'checkpoint') { record.revision++; record.data.context_hash = 'b'.repeat(64); record.data.context_note = null; record.checkpoints.push({ id: `checkpoint-${record.checkpoints.length + 1}`, created_at: '2026-10-05T12:01:00Z', data: { code: extra.body.code, explanation: extra.body.explanation } }); }
      if (match[2] === 'import-submission') { record.revision++; record.data.context_hash = 'b'.repeat(64); record.data.context_note = null; record.checkpoints.push({ id: `checkpoint-${record.checkpoints.length + 1}`, created_at: '2026-10-05T12:01:00Z', data: { code: 'MY PRIVATE SUBMITTED CODE', explanation: extra.body.explanation, submission_ref: extra.body.submission_ref } }); }
      if (match[2] === 'export-context') { record.revision++; record.data.context_note = { id: `note-${record.id}`, revision: 1, title: 'Exact practice note', sha256: hash }; }
      if (match[2] === 'preview-run') return { item: { kind: extra.body.kind, prompt: 'EXACT REVIEWED PROMPT', prompt_sha256: hash } };
      if (match[2] === 'run') { record.revision++; record.data.pending = { state: 'running', turn_id: 'turn-1' }; }
      if (match[2] === 'transition') { record.revision++; record.data.state = extra.body.action === 'resume' ? 'ready' : extra.body.action === 'pause' ? 'paused' : 'finished'; }
      return { item: structuredClone(record) };
    }
    throw new Error(`Unexpected UI route ${path}`);
  }, busy(control, run) { control.disabled = true; const job = Promise.resolve().then(run).finally(() => { control.disabled = false; }); jobs.push(job); return job; }, confirmAction: async (...args) => { confirmations.push(args); return options.confirm ? await options.confirm(...args) : true; } });
  t.after(() => { ui.reset(); for (const [name, descriptor] of globals) { if (descriptor) Object.defineProperty(globalThis, name, descriptor); else delete globalThis[name]; } });
  const find = predicate => { const node = walk(root).find(predicate); assert(node, 'Expected LeetCode UI node'); return node; };
  return { ui, root, calls, data, sessions, grants, confirmations, find, get recognition() { return recognition; }, get aborts() { return aborts; }, button: label => find(node => node.tagName === 'button' && node.textContent === label), field(label) { const caption = find(node => node.tagName === 'label' && node.textContent === label); return find(node => node.id === caption.htmlFor); }, async click(label) { const node = this.button(label); assert.equal(node.disabled, false, label); fire(node); await jobs.at(-1)?.catch(() => {}); await Promise.resolve(); }, async submit(label) { const control = this.button(label), form = walk(root).find(node => node.tagName === 'form' && walk(node).includes(control)); assert.equal(control.disabled, false, label); fire(form, 'submit'); await jobs.at(-1)?.catch(() => {}); await Promise.resolve(); }, startSubmit(label) { const control = this.button(label), form = walk(root).find(node => node.tagName === 'form' && walk(node).includes(control)); fire(form, 'submit'); return jobs.at(-1); }, async open(id = 'practice-1') { await ui.refresh(); const row = find(node => node.tagName === 'article' && node.children.some(child => child.tagName === 'button' && child.attributes.get('aria-label')?.includes('Open coding practice:')) && sessions.find(item => item.id === id)?.created_at === '2026-10-05T12:00:00Z'); const control = row.children.find(node => node.tagName === 'button'); fire(control); await jobs.at(-1); }, writes() { return calls.filter(row => row.method === 'POST'); } };
}

test('LCUI01: refresh shows bounded failed/repeated history but never imports, fetches submitted code, grants or runs', async t => { const h = harness(t); await h.ui.refresh(); assert.match(h.root.textContent, /Wrong Answer/); assert.match(h.root.textContent, /Accepted/); assert.match(h.root.textContent, /2 observed attempts/); assert.match(h.root.textContent, /not your complete account/); assert.equal(h.writes().length, 0); assert.equal(h.root.textContent.includes('MY PRIVATE SUBMITTED CODE'), false); });
test('LCUI02: private credential clears before dispatch and never appears in confirmation, snapshot, or retry key', async t => { let cookieDuringDispatch; const h = harness(t, { handle: (path, extra) => { if (path === '/leetcode/connect') cookieDuringDispatch = h.field('Optional LEETCODE_SESSION cookie').value; } }); await h.ui.refresh(); h.field('LeetCode username').value = 'student'; h.field('Optional LEETCODE_SESSION cookie').value = 'PRIVATE COOKIE CANARY'; await h.submit('Review connection'); const sent = h.calls.find(row => row.path === '/leetcode/connect'); assert.equal(sent.body.session, 'PRIVATE COOKIE CANARY'); assert.equal(cookieDuringDispatch, ''); assert.equal(h.field('Optional LEETCODE_SESSION cookie').value, ''); assert.equal(JSON.stringify(h.confirmations).includes('PRIVATE COOKIE CANARY'), false); assert.equal('idempotencyKey' in sent, false); assert.equal(h.root.textContent.includes('PRIVATE COOKIE CANARY'), false); });
test('LCUI03: cancelled private connection or edited credential during consent dispatches nothing', async t => { const entered = deferred(), release = deferred(), h = harness(t, { confirm: () => { entered.resolve(); return release.promise; } }); await h.ui.refresh(); h.field('LeetCode username').value = 'student'; h.field('Optional LEETCODE_SESSION cookie').value = 'ORIGINAL COOKIE'; const pending = h.startSubmit('Review connection'); await entered.promise; h.field('Optional LEETCODE_SESSION cookie').value = 'CHANGED COOKIE'; release.resolve(true); await pending; assert.equal(h.writes().length, 0); });
test('LCUI04: public-only account cannot fetch private code; reviewed history bounds are exact', async t => { const h = harness(t, { connection: { state: 'public', username: 'student' } }); await h.ui.refresh(); assert.equal(h.button('Review this submitted code').disabled, true); h.field('Maximum attempts to read').value = '50'; await h.submit('Review history import'); assert.deepEqual(h.calls.find(row => row.path === '/leetcode/sync').body, { confirmed: true, limit: 50, include_contest: false }); assert.equal(h.calls.some(row => row.path.includes('/submissions/')), false); });
test('LCUI05: single submitted code read needs explicit review and stays out of model context', async t => { const h = harness(t); await h.ui.refresh(); await h.click('Review this submitted code'); const sent = h.calls.find(row => row.path === '/leetcode/submissions/111'); assert.deepEqual(sent.body, { snapshot_id: 'saved-history', confirmed: true }); assert.match(h.root.textContent, /MY PRIVATE SUBMITTED CODE/); assert.match(h.root.textContent, /not executed locally or sent to AI/); assert.equal(h.calls.some(row => row.path.includes('/run') || row.path === '/agent-grants' && row.method), false); });
test('LCUI06: coding drafts survive refresh and navigation without becoming checkpoints or model inputs', async t => { const h = harness(t); await h.open(); h.field('Your own code').value = 'MY UNSAVED CODE'; fire(h.field('Your own code'), 'input'); h.field('Explain your approach in your own words').value = 'MY UNSAVED EXPLANATION'; fire(h.field('Explain your approach in your own words'), 'input'); h.ui.pause(); await h.ui.refresh(); assert.equal(h.field('Your own code').value, 'MY UNSAVED CODE'); assert.equal(h.field('Explain your approach in your own words').value, 'MY UNSAVED EXPLANATION'); assert.equal(h.writes().length, 0); assert.equal(h.button('Review AI coaching request').disabled, true); });
test('LCUI07: saved checkpoint, exact note, one-note grant and reviewed AI request remain separate', async t => { const h = harness(t); await h.open(); h.field('Your own code').value = 'def solve(nums):\n    return []'; fire(h.field('Your own code'), 'input'); h.field('Explain your approach in your own words').value = 'I need to track prior values.'; fire(h.field('Explain your approach in your own words'), 'input'); await h.submit('Save my exact checkpoint'); assert.equal(h.sessions[0].checkpoints.length, 1); assert.equal(h.sessions[0].data.context_note, null); assert.equal(h.calls.some(row => row.path.endsWith('/run')), false); await h.click('Review private coaching note'); await h.click('Allow this exact note for Codex'); const grant = h.calls.find(row => row.path === '/agent-grants' && row.method); assert.deepEqual(grant.body.document_ids, ['note-practice-1']); assert.deepEqual(grant.body.task_ids, []); assert.deepEqual(grant.body.source_entry_ids, []); h.field('What should the interviewer do next?').value = 'review'; await h.click('Review AI coaching request'); const run = h.calls.find(row => row.path.endsWith('/run')); assert.equal(run.body.kind, 'review'); assert.equal(run.body.prompt_sha256, hash); assert.equal(run.body.grant_id, 'grant-1'); assert.match(h.confirmations.at(-1)[0], /EXACT REVIEWED PROMPT/); assert.equal(h.calls.some(row => /submit_solution|run_code/.test(row.path)), false); });
test('LCUI08: a broader grant with unrelated material cannot enable AI coaching', async t => { const row = session(); row.data.context_note = { id: 'exact-note', revision: 1, title: 'Exact note' }; const base = { destination: 'codex', state: 'active', expires_at: new Date(Date.now() + 300000).toISOString(), pins: { documents: [{ id: 'exact-note', revision: 1 }, { id: 'unrelated', revision: 1 }], tasks: [], source_entries: [] } }, h = harness(t, { sessions: [row], grants: [{ ...base, id: 'broad' }] }); await h.open(); assert.equal(h.button('Review AI coaching request').disabled, true); assert.equal(h.writes().length, 0); });
test('LCUI09: pausing stops microphone, discards late transcript and never submits the answer', async t => { const h = harness(t); await h.open(); await h.click('Talk through my approach'); const old = h.recognition; h.ui.pause(); old.onresult({ resultIndex: 0, results: [Object.assign([{ transcript: 'LATE VOICE CANARY' }], { isFinal: true })] }); assert.equal(h.aborts, 1); assert.equal(h.field('Explain your approach in your own words').value, ''); assert.equal(h.writes().length, 0); });
test('LCUI10: reset during consent cannot revive a private connection or draft', async t => { const entered = deferred(), release = deferred(), h = harness(t, { confirm: () => { entered.resolve(); return release.promise; } }); await h.ui.refresh(); h.field('LeetCode username').value = 'student'; h.field('Optional LEETCODE_SESSION cookie').value = 'PRIVATE RESET CANARY'; const pending = h.startSubmit('Review connection'); await entered.promise; h.ui.reset(); release.resolve(true); await pending; assert.equal(h.writes().length, 0); assert.equal(h.field('Optional LEETCODE_SESSION cookie').value, ''); assert.equal(h.root.textContent.includes('student · private'), false); });
test('LCUI11: unsafe attempt URLs are displayed as text, never made clickable or executed', async t => { const h = harness(t); h.data.snapshots[0].data.attempts[0].url = 'javascript:alert(1)'; await h.ui.refresh(); const links = walk(h.root).filter(node => node.tagName === 'a'); assert(links.every(node => node.href.startsWith('https://leetcode.com/'))); assert.equal(links.some(node => node.href.startsWith('javascript:')), false); });
test('LCUI12: unsaved changes block coaching even when the exact previous checkpoint has a valid grant', async t => { const row = session(); row.data.context_note = { id: 'exact-note', revision: 1, title: 'Exact note' }; row.checkpoints.push({ id: 'saved', data: { code: 'SAVED CODE', explanation: 'Saved explanation' } }); const h = harness(t, { sessions: [row], grants: [{ id: 'exact', destination: 'codex', state: 'active', expires_at: new Date(Date.now() + 300000).toISOString(), pins: { documents: [{ id: 'exact-note', revision: 1 }], tasks: [], source_entries: [] } }] }); await h.open(); assert.equal(h.button('Review AI coaching request').disabled, false); h.field('Your own code').value = 'UNSAVED CODE'; fire(h.field('Your own code'), 'input'); assert.equal(h.button('Review AI coaching request').disabled, true); assert.equal(h.writes().length, 0); });
test('LCUI13: normal sign-in is the primary path and needs no copied credential or typed username', async t => { const h = harness(t, { connection: { state: 'disconnected' } }); await h.ui.refresh(); await h.click('1. Open LeetCode sign-in'); assert.equal(h.button('2. Check my signed-in account').disabled, false); await h.submit('2. Check my signed-in account'); const start = h.calls.find(row => row.path === '/leetcode/browser/start'), check = h.calls.find(row => row.path === '/leetcode/browser/check'); assert.deepEqual(start.body, { confirmed: true }); assert.deepEqual(check.body, { confirmed: true }); assert.equal(h.calls.some(row => row.path === '/leetcode/connect' || row.path === '/leetcode/sync'), false); assert.match(h.root.textContent, /No cookie copying is needed/); });
test('LCUI14: forget saved browser sign-in requires explicit review and disables recheck afterward', async t => { const h = harness(t, { browser: { state: 'open', profile_retained: true, owner: true, capability: { state: 'available' } } }); await h.ui.refresh(); await h.click('Forget saved LeetCode sign-in'); assert.deepEqual(h.calls.find(row => row.path === '/leetcode/browser/forget').body, { confirmed: true }); assert.match(h.confirmations[0][0], /delete its saved local sign-in profile/); assert.equal(h.button('2. Check my signed-in account').disabled, true); assert.equal(h.button('Forget saved LeetCode sign-in').disabled, true); });
test('LCUI15: another browser cannot recheck or forget the owned sign-in profile', async t => { const h = harness(t, { connection: { state: 'disconnected' }, browser: { state: 'open', profile_retained: true, owner: false, capability: { state: 'available' } } }); await h.ui.refresh(); assert.equal(h.button('2. Check my signed-in account').disabled, true); assert.equal(h.button('Forget saved LeetCode sign-in').disabled, true); assert.equal(h.writes().length, 0); });
test('LCUI16: selected submitted answer is imported only with reviewed own explanation, before separate AI sharing', async t => { const h = harness(t); await h.open(); await h.click('Review this submitted code'); h.field('Explain what you learned from this saved submission').value = 'I overlooked the duplicate-value case.'; fire(h.field('Explain what you learned from this saved submission'), 'input'); await h.ui.refresh(); assert.equal(h.field('Explain what you learned from this saved submission').value, 'I overlooked the duplicate-value case.'); await h.submit('Review this attempt as a private checkpoint'); const call = h.calls.find(row => row.path.endsWith('/import-submission')); assert.deepEqual(call.body.submission_ref, { id: 'submission-1', revision: 1, sha256: hash }); assert.equal(call.body.explanation, 'I overlooked the duplicate-value case.'); assert.equal(h.sessions[0].checkpoints[0].data.code, 'MY PRIVATE SUBMITTED CODE'); assert.equal(h.sessions[0].data.context_note, null); assert.equal(h.calls.some(row => row.path.endsWith('/run') || row.path === '/agent-grants' && row.method), false); });
test('LCUI17: account change during private submission consent cannot fetch historical code', async t => { const entered = deferred(), release = deferred(), h = harness(t, { confirm: () => { entered.resolve(); return release.promise; } }); await h.ui.refresh(); const pending = (async () => h.click('Review this submitted code'))(); await entered.promise; h.data.connection = { state: 'private', username: 'another-student' }; await h.ui.refresh(); release.resolve(true); await pending; assert.equal(h.calls.some(row => row.path.startsWith('/leetcode/submissions/')), false); });
test('LCUI18: canceled primary sign-in consent neither opens Chrome nor reads an account', async t => { const h = harness(t, { confirm: () => false }); await h.ui.refresh(); await h.click('1. Open LeetCode sign-in'); assert.equal(h.writes().length, 0); });
test('LCUI19: retained code opens explicitly after disconnect, with no live calls or automatic code reveal', async t => { const h = harness(t, { connection: { state: 'disconnected' } }); h.data.saved_submissions = [{ id: 'submission-1', revision: 1, sha256: hash, title: 'Two Sum', username: 'student', submission_id: '111', snapshot_id: 'saved-history' }]; await h.ui.refresh(); assert.equal(h.root.textContent.includes('MY PRIVATE SUBMITTED CODE'), false); await h.click('Open saved submitted code'); assert.match(h.root.textContent, /MY PRIVATE SUBMITTED CODE/); assert.equal(h.calls.some(row => row.path === '/leetcode/saved-submissions/submission-1'), true); assert.equal(h.writes().length, 0); assert.equal(h.calls.some(row => row.path === '/leetcode/connect' || row.path.startsWith('/leetcode/submissions/') || row.path === '/leetcode/browser/check'), false); });
test('LCUI20: optional expected username is checked only when the student chooses to enter it', async t => { const h = harness(t, { browser: { state: 'open', profile_retained: true, owner: true, capability: { state: 'available' } } }); await h.ui.refresh(); h.field('Optional expected LeetCode username').value = 'student'; await h.submit('2. Check my signed-in account'); assert.deepEqual(h.calls.find(row => row.path === '/leetcode/browser/check').body, { username: 'student', confirmed: true }); });
test('LCUI21: exact history coaching export creates only a local note and instructs explicit Codex or Claude selection', async t => { const h = harness(t); await h.ui.refresh(); await h.click('Save this history for AI coaching'); const writes = h.writes(); assert.equal(writes.length, 1); assert.equal(writes[0].path, '/leetcode/snapshots/saved-history/export-context'); assert.deepEqual(writes[0].body, { expected_revision: 1, sha256: hash, confirmed: true }); assert.match(h.root.textContent, /ONLY SELECTED HISTORY, WITHOUT SOURCE CODE OR COOKIE/); assert.match(h.root.textContent, /allow only it for Codex or Claude/); assert.equal(h.calls.some(row => row.path === '/agent-grants' && row.method || row.path.endsWith('/run')), false); });
test('LCUI22: over-budget history note offers a smaller reviewed import without silent trimming, grants or turns', async t => { const h = harness(t, { handle: path => path.endsWith('/export-context') ? Promise.reject(Object.assign(new Error('BUDGET_EXCEEDED'), { code: 'BUDGET_EXCEEDED' })) : undefined }); await h.ui.refresh(); await h.click('Save this history for AI coaching'); assert.match(h.root.textContent, /smaller import of 20 or 50 attempts/); assert.match(h.root.textContent, /Nothing was silently trimmed or shared/); assert.equal(h.calls.some(row => row.path === '/agent-grants' && row.method || row.path.endsWith('/run')), false); });
test('LCUI23: problem statement stays visible and the language template is an explicit local draft only', async t => { const h = harness(t); await h.open(); assert.match(h.root.textContent, /Return the two indices/); assert.equal(h.field('Your own code').value, ''); await h.click('Use the problem’s language template'); assert.equal(h.field('Your own code').value, '# starter'); assert.match(h.root.textContent, /Unsaved draft/); assert.equal(h.writes().length, 0); assert.equal(h.button('Review AI coaching request').disabled, true); });
test('LCUI24: canceling a manual credential review clears its form and never connects', async t => { const h = harness(t, { confirm: () => false }); await h.ui.refresh(); h.field('LeetCode username').value = 'student'; h.field('Optional LEETCODE_SESSION cookie').value = 'CANCELED PRIVATE CANARY'; await h.submit('Review connection'); assert.equal(h.field('Optional LEETCODE_SESSION cookie').value, ''); assert.equal(h.writes().length, 0); });
test('LCUI25: exact UTF-8 checkpoint bounds preserve oversized multibyte drafts and do not send them', async t => { const h = harness(t); await h.open(); const oversized = '界'.repeat(4001); h.field('Your own code').value = oversized; fire(h.field('Your own code'), 'input'); await h.submit('Save my exact checkpoint'); assert.match(h.root.textContent, /maximum 12,000 UTF-8 bytes/); assert.match(h.root.textContent, /draft is preserved/); assert.equal(h.field('Your own code').value, oversized); assert.equal(h.writes().length, 0); assert.equal(h.confirmations.length, 0); });
test('LCUI26: saved-attempt explanation uses the real service byte bound and preserves oversized text', async t => { const h = harness(t); await h.open(); await h.click('Review this submitted code'); const explanation = h.field('Explain what you learned from this saved submission'); explanation.value = '界'.repeat(2001); fire(explanation, 'input'); const prior = h.writes().length; await h.submit('Review this attempt as a private checkpoint'); assert.match(h.root.textContent, /maximum 6,000 UTF-8 bytes/); assert.equal(explanation.value, '界'.repeat(2001)); assert.equal(h.writes().length, prior); assert.equal(h.calls.some(row => row.path.endsWith('/import-submission')), false); });
test('LCUI27: a later private connection cannot fetch code from an earlier public snapshot lacking private IDs', async t => { const h = harness(t); for (const [index, attempt] of h.data.snapshots[0].data.attempts.entries()) { attempt.id = `public-observation-${index}`; attempt.private_detail_available = false; } await h.ui.refresh(); assert.equal(h.button('Review this submitted code').disabled, true); assert.match(h.root.textContent, /public sample has no private submission IDs/); assert.match(h.root.textContent, /fresh private history snapshot/); assert.equal(h.calls.some(row => row.path.startsWith('/leetcode/submissions/')), false); assert.equal(h.writes().length, 0); });
test('LCUI28: refreshing a grant crossing expiry disables coaching while preserving the exact draft', async t => { const row = session(); row.data.context_note = { id: 'exact-note', revision: 1, title: 'Exact note' }; const grants = [{ id: 'exact', destination: 'codex', state: 'active', expires_at: new Date(Date.now() + 300000).toISOString(), max_bytes: 256000, used_bytes: 0, pins: { documents: [{ id: 'exact-note', revision: 1 }], tasks: [], source_entries: [] } }], h = harness(t, { sessions: [row], grants }); await h.open(); assert.equal(h.button('Review AI coaching request').disabled, false); grants[0].expires_at = new Date(Date.now() - 1000).toISOString(); await h.ui.refresh(); assert.equal(h.button('Review AI coaching request').disabled, true); assert.equal(h.button('Allow this exact note for Codex').disabled, false); assert.equal(h.writes().length, 0); });
test('LCUI29: refreshing exhausted read budget disables coaching and offers a fresh exact sharing selection', async t => { const row = session(); row.data.context_note = { id: 'exact-note', revision: 1, title: 'Exact note' }; const grants = [{ id: 'exact', destination: 'codex', state: 'active', expires_at: new Date(Date.now() + 300000).toISOString(), max_bytes: 256000, used_bytes: 0, pins: { documents: [{ id: 'exact-note', revision: 1 }], tasks: [], source_entries: [] } }], h = harness(t, { sessions: [row], grants }); await h.open(); assert.equal(h.button('Review AI coaching request').disabled, false); grants[0].used_bytes = grants[0].max_bytes; await h.ui.refresh(); assert.equal(h.button('Review AI coaching request').disabled, true); assert.equal(h.button('Allow this exact note for Codex').disabled, false); assert.equal(h.writes().length, 0); });
test('LCUI30: history coverage is readable prose rather than an unbroken technical JSON string', async t => { const h = harness(t); h.data.snapshots[0].data.coverage = { mode: 'private_bounded_pages', requested_limit: 20, retrieved_count: 2, has_next_page: false, internal_field_canary: 'UNBROKEN_TECHNICAL_CANARY'.repeat(100) }; await h.ui.refresh(); assert.match(h.root.textContent, /Read 2 of a maximum 20 attempts/); assert.match(h.root.textContent, /LeetCode reported no more pages/); assert.match(h.root.textContent, /partial practice record/); assert.equal(h.root.textContent.includes('UNBROKEN_TECHNICAL_CANARY'), false); assert.equal(h.root.textContent.includes('requested_limit'), false); assert.equal(h.writes().length, 0); });
