import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { LocalStore } from '../packages/local-storage/src/index.mjs';
import { createLeetCodeService, LEETCODE_FORMATS, analyzeLeetCodeSnapshot, leetcodePlainText } from '../apps/local-runtime/src/leetcode-service.mjs';
import { createLeetCodeRoutes } from '../apps/local-runtime/src/leetcode-routes.mjs';

import { leetcodeFixtureClient } from './fixtures/leetcode-test-support.mjs';
const user = 'FixtureStudent', secret = 'SYNTHETIC_SESSION_FOR_TEST_ONLY_123';

function fixture(t, extra = {}) { const parent = mkdtempSync(join(tmpdir(), 'learnbridge-leetcode-service-')), store = LocalStore.open({ root: join(parent, 'private') }), client = leetcodeFixtureClient(extra), service = createLeetCodeService({ store, clientFactory: client.clientFactory }); t.after(async () => { await service.close(); store.close(); rmSync(parent, { recursive: true, force: true }); }); return { parent, store, client, service, connect: () => service.connect({ username: user, session: secret, confirmed: true }) }; }
const syncInput = { confirmed: true, limit: 50, include_contest: true };
const isCode = code => error => error.code === code;

test('private bounded pages preserve failed and repeated attempts plus judge/contest meanings', async t => { const f = fixture(t); await f.connect(); const snapshot = await f.service.sync(syncInput); assert.equal(snapshot.data.attempts.length, 45); assert.deepEqual(f.client.calls.filter(row => row.name === 'get_all_submissions').map(row => row.args), [{offset:0,limit:20},{offset:20,limit:20},{offset:40,limit:10}]); assert.equal(snapshot.data.coverage.has_next_page, false); assert.equal(snapshot.data.coverage.complete_history_claim, false); assert.equal(snapshot.data.coverage.private_code_included, false); const analytics = f.service.state().analytics; assert.equal(analytics.attempt_count, 45); assert.equal(analytics.distinct_problems, 2); assert.equal(analytics.accepted_attempts, 22); assert.equal(analytics.nonaccepted_attempts, 23); assert.equal(analytics.mastery_claim, false); assert.equal(analytics.skill_score, null); assert(analytics.recommendations.every(row => row.evidence_ids.every(id => snapshot.data.attempts.some(attempt => attempt.id === id)))); assert(!JSON.stringify(snapshot).includes(secret)); });

test('public connection retrieves recent attempts without claiming authenticated ownership or full code', async t => { const f = fixture(t); await f.service.connect({ username: user, confirmed: true }); const snapshot = await f.service.sync(syncInput); assert.equal(f.service.state().connection.state, 'public'); assert.equal(snapshot.data.coverage.mode, 'public_recent_only'); assert.equal(snapshot.data.attempts.length,20); assert(snapshot.data.attempts.every(row => row.id.startsWith('public-') && row.private_detail_available === false)); assert(!f.client.calls.some(row => row.name === 'get_user_status' || row.name === 'get_all_submissions')); await assert.rejects(f.service.fetchSubmission('10000', { snapshot_id: snapshot.id, confirmed:true }), isCode('SCOPE_DENIED')); });

test('selected private code is an explicit separate read of a retrieved submission', async t => { const f = fixture(t); await f.connect(); const snapshot = await f.service.sync(syncInput); assert(!f.client.calls.some(row => row.name === 'get_problem_submission_report')); await assert.rejects(f.service.fetchSubmission('99999',{snapshot_id:snapshot.id,confirmed:true}),isCode('SCOPE_DENIED')); const report = await f.service.fetchSubmission('10000',{snapshot_id:snapshot.id,confirmed:true}); assert.equal(report.data.code, 'def two_sum(nums, target):\n    return [0, 1]'); assert.equal(report.data.correctness,'platform_reported_not_locally_executed'); assert.equal(report.data.snapshot_ref.sha256,snapshot.sha256); assert.equal(report.data.runtime,'20 ms'); assert.equal(report.data.total_correct,63); assert.equal(f.client.calls.filter(row=>row.name==='get_problem_submission_report').length,1); });

test('a switched account rejects old selected history and closes transient credentials', async t => { const f = fixture(t); await f.connect(); const snapshot = await f.service.sync(syncInput); f.client.switchUser('OtherStudent'); await assert.rejects(f.service.fetchSubmission('10000',{snapshot_id:snapshot.id,confirmed:true}),isCode('SCOPE_DENIED')); assert.equal(f.service.state().connection.state,'disconnected'); assert.equal(f.client.closed.length,1); assert(!f.client.calls.some(row=>row.name==='get_problem_submission_report')); assert.equal(f.service.snapshot(snapshot.id).data.username,user); });

test('expired identity stops imports and does not write a snapshot', async t => { const f = fixture(t); await f.connect(); f.client.expire(); await assert.rejects(f.service.sync(syncInput),isCode('AUTH_REQUIRED')); assert.equal(f.service.snapshots().length,0); assert.equal(f.service.state().connection.state,'disconnected'); });

test('account expiry between last page and commit discards imported data', async t => { const f = fixture(t,{count:2}); await f.connect(); f.client.handle((name,args)=>{ if(name==='get_all_submissions') { f.client.expire(); return {submissions:f.client.rows,hasNext:false}; } }); await assert.rejects(f.service.sync(syncInput),isCode('AUTH_REQUIRED')); assert.equal(f.service.snapshots().length,0); });

test('same-key sync retries reuse exact observation; changed request conflicts', async t => { const f=fixture(t); await f.connect(); const opts={idempotencyKey:randomUUID()}, first=await f.service.sync(syncInput,opts), count=f.client.calls.filter(row=>row.name==='get_all_submissions').length; const second=await f.service.sync(syncInput,opts); assert.equal(second.id,first.id); assert.equal(f.client.calls.filter(row=>row.name==='get_all_submissions').length,count); await assert.rejects(f.service.sync({...syncInput,limit:20},opts),isCode('REVISION_CONFLICT')); });

test('bounded history stops at requested limit and admits a next page remains', async t => { const f=fixture(t,{count:120}); await f.connect(); const snapshot=await f.service.sync({...syncInput,limit:20,include_contest:false}); assert.equal(snapshot.data.attempts.length,20); assert.equal(snapshot.data.coverage.has_next_page,true); assert.equal(snapshot.data.coverage.provider_page_end_observed,false); assert(!f.client.calls.some(row=>row.name==='get_user_contest_ranking')); });

test('selected problem preserves plain text and starter template, never upstream hints', async t => { const f=fixture(t); await f.connect(); const problem=await f.service.fetchProblem({slug:'two-sum',confirmed:true}); assert.equal(problem.data.content,'Return two indices. <tag>'); assert.equal(problem.data.code_snippets[0].lang_slug,'python3'); assert(!JSON.stringify(problem).includes('SPOILER_CANARY')); assert(!JSON.stringify(problem).includes('UNTRUSTED_SCRIPT_CANARY')); assert.equal(f.service.problem(problem.id).sha256,problem.sha256); });

test('private session rejects Cookie headers, URLs and unconfirmed connection', async t => { const f=fixture(t); for (const session of ['Cookie: foo=bar','https://attacker.test/','abc\r\nHeader: x']) await assert.rejects(f.service.connect({username:user,session,confirmed:true}),isCode('INVALID_INPUT')); await assert.rejects(f.service.connect({username:user,session:secret,confirmed:false}),isCode('CONSENT_REQUIRED')); assert.equal(f.client.calls.length,0); });

test('concurrent disconnect invalidates an in-flight read without storing or replaying', async t => { const f=fixture(t); await f.connect(); let release, arrived; const reached=new Promise(resolve=>arrived=resolve); f.client.handle(async name=>{if(name==='get_all_submissions'){arrived(); await new Promise(resolve=>release=resolve); return {submissions:f.client.rows.slice(0,20),hasNext:true};}}); const running=f.service.sync({...syncInput,limit:20}); await reached; await f.service.disconnect(); release(); await assert.rejects(running,isCode('CONSENT_REQUIRED')); assert.equal(f.service.snapshots().length,0); });

test('revoked paired authority discards a completed response before local commit', async t => { const f=fixture(t); await f.connect(); let allowed=true; f.client.handle(name=>{if(name==='get_all_submissions'){allowed=false; return {submissions:f.client.rows.slice(0,20),hasNext:true};}}); await assert.rejects(f.service.sync({...syncInput,limit:20},{authorize:()=>allowed}),isCode('CONSENT_REQUIRED')); assert.equal(f.service.snapshots().length,0); });

test('snapshot and selected code survive restore while credentials and connection do not', async t => { const f=fixture(t,{count:2}); await f.connect(); const snapshot=await f.service.sync(syncInput), report=await f.service.fetchSubmission('10000',{snapshot_id:snapshot.id,confirmed:true}), backup=join(f.parent,'backup'); await f.store.backup(backup); await LocalStore.restore({backupRoot:backup,root:join(f.parent,'restored')}); const restored=LocalStore.open({root:join(f.parent,'restored')}); t.after(()=>restored.close()); const disconnected=createLeetCodeService({store:restored,clientFactory:f.client.clientFactory}); t.after(()=>disconnected.close()); assert.equal(disconnected.state().connection.state,'disconnected'); assert.equal(disconnected.snapshot(snapshot.id).sha256,snapshot.sha256); assert.equal(restored.getWorkspaceRecord(report.id).data.code,report.data.code); assert(!readFileSync(join(backup,'learnbridge.sqlite')).includes(Buffer.from(secret))); });

test('analytics withstands untrusted dictionary keys and makes no unobserved mastery claim',()=>{const a=analyzeLeetCodeSnapshot({attempts:[{id:'x',slug:'p',title:'p',status:'__proto__',language:'constructor'}],coverage:{complete_history_claim:false}}); assert.equal(a.outcomes.__proto__,1); assert.equal(a.languages.constructor,1); assert.equal(a.skill_score,null); assert.equal(a.mastery_claim,false); assert.equal(leetcodePlainText('<style>x</style><p>A &amp; B</p>'),'A & B');});

test('pending and unknown outcomes never imply accepted practice in recommendations',()=>{for(const status of ['Pending','Judging','Unrecognized provider result']){const a=analyzeLeetCodeSnapshot({attempts:[{id:'x',slug:'p',title:'p',status,language:'python3',is_pending:status!=='Unrecognized provider result'}]});assert.equal(a.accepted_attempts,0);assert.equal(a.terminal_failure_attempts,0);assert.equal(a.recommendations.length,1);assert(!a.recommendations[0].reason.includes('were accepted'));assert(a.recommendations[0].reason.includes('pending or unknown'));assert.deepEqual(a.recommendations[0].evidence_ids,['x']);}});

test('paired browser nonce exclusively owns live connection while saved observations remain local', async t=>{const f=fixture(t), routes=createLeetCodeRoutes({store:f.store,clientFactory:f.client.clientFactory}); t.after(()=>routes.clear()); const session={nonce:'first-paired-browser'}, other={nonce:'second-paired-browser'}, invoke=async(route,body,chosen=session,method='POST')=>routes.handle({route,method,session:chosen,privateBody:async()=>body,stillAuthorized:()=>true,sourceOperation:fn=>fn(new AbortController().signal)}); await invoke('/leetcode/connect',{username:user,session:secret,confirmed:true}); const hidden=await invoke('/leetcode/state',null,other,'GET'); assert.equal(hidden.data.connection.owned_by_other_browser,true); await assert.rejects(invoke('/leetcode/sync',syncInput,other),isCode('CONSENT_REQUIRED')); const saved=await invoke('/leetcode/sync',syncInput); assert.equal(saved.data.item.data.attempts.length,45); await invoke('/leetcode/disconnect',{confirmed:true}); assert.equal(routes.service.state().connection.state,'disconnected'); });

test('transport AUTH_EXPIRED clears connected authority and routes map it to reconnect rather than local logout', async t=>{ const f=fixture(t), routes=createLeetCodeRoutes({store:f.store,clientFactory:f.client.clientFactory}); t.after(()=>routes.clear()); const session={nonce:'browser-owner'}, invoke=(route,body)=>routes.handle({route,method:'POST',session,privateBody:async()=>body,stillAuthorized:()=>true,sourceOperation:fn=>fn(new AbortController().signal)}); await invoke('/leetcode/connect',{username:user,session:secret,confirmed:true}); f.client.handle(name=>{if(name==='get_user_status'){const error=new Error('private diagnostic'); error.code='AUTH_EXPIRED'; throw error;}}); await assert.rejects(invoke('/leetcode/sync',syncInput),error=>error.status===409 && error.code==='LEETCODE_AUTH_REQUIRED' && !error.message.includes('private diagnostic')); assert.equal(routes.service.state().connection.state,'disconnected'); assert.equal(routes.service.snapshots().length,0); });

test('pending judge results are counted separately and never treated as debugging failures',()=>{const analytics=analyzeLeetCodeSnapshot({attempts:[{id:'x',slug:'p',title:'p',status:'Judging',language:'python3',is_pending:true}]}); assert.equal(analytics.pending_attempts,1); assert.equal(analytics.terminal_failure_attempts,0); assert(!analytics.recommendations.some(row=>row.title==='Practise debugging and test selection'));});

test('missing report owner rejects a private code response at the service boundary',async t=>{const f=fixture(t); await f.connect(); const snapshot=await f.service.sync(syncInput); f.client.handle(name=>{if(name==='get_problem_submission_report')return {id:'10000',titleSlug:'valid-parentheses',code:'private',lang:'python3'};}); await assert.rejects(f.service.fetchSubmission('10000',{snapshot_id:snapshot.id,confirmed:true}),isCode('SCOPE_DENIED')); assert.equal(f.store.listWorkspaceRecords({kind:'career_item'}).filter(row=>row.data.format===LEETCODE_FORMATS.submission).length,0);});

test('owned browser rotation changes only transient client after exact account check', async t=>{const f=fixture(t); await f.connect(); await f.service.refreshSession('SYNTHETIC_ROTATED_SESSION_ONLY_456'); assert.equal(f.client.closed.length,1); assert.equal(f.service.state().connection.username,user); assert(!JSON.stringify(f.service.state()).includes('SYNTHETIC_ROTATED')); f.client.switchUser('OtherStudent'); await assert.rejects(f.service.refreshSession('SYNTHETIC_OTHER_SESSION_ONLY_789'),isCode('SCOPE_DENIED')); assert.equal(f.service.state().connection.state,'disconnected');});

test('history note export pins exactly observed attempts and remains unshared',async t=>{const f=fixture(t,{count:5});await f.connect();const snapshot=await f.service.sync({...syncInput,limit:20});await assert.rejects(async()=>f.service.exportSnapshot(snapshot.id,{expected_revision:2,sha256:snapshot.sha256,confirmed:true}),isCode('REVISION_CONFLICT'));const note=f.service.exportSnapshot(snapshot.id,{expected_revision:1,sha256:snapshot.sha256,confirmed:true});const context=JSON.parse(note.content);assert.equal(context.attempts.length,5);assert.equal(context.private_code_included,false);assert.equal(context.mastery_claim,false);assert.equal(note.sharing,'not_granted');assert.equal(f.store.listAgentGrants({destination:'codex'}).length,0);assert(!note.content.includes(secret));});
