import test from 'node:test';
import assert from 'node:assert/strict';
import { mountOverviewUI } from '../apps/local/public/overview.js';
class Node {
  constructor(tag, cls='', text='') {this.tag=tag;this.text=text;this.children=[];this.listeners={};}
  append(...children){this.children.push(...children);} replaceChildren(...children){this.children=children;}
  addEventListener(event,callback){this.listeners[event]=callback;}
  get textContent(){return this.text+this.children.map(child=>child.textContent).join(' ');}
}
const values={'/focus/context':{open_session:{data:{title:'<script>private focus</script>',state:'paused'}}},'/reminders/inbox':{items:[{acknowledged_at:null},{acknowledged_at:'2026-10-04T16:00:00Z'}]},'/practice/due':{total_due:3,unavailable:[]},'/task-proposals':{items:[{state:'awaiting_review'},{state:'accepted'}]},'/writing/items':{items:[{state:'awaiting_review'},{state:'needs_reconciliation'},{state:'accepted'}]}};
function harness(request){const root=new Node('root'),calls=[],navigation=[];const ui=mountOverviewUI({root,element:(...args)=>new Node(...args),navigate:page=>navigation.push(page),request:async(path,...rest)=>{calls.push([path,...rest]);return request?request(path):structuredClone(values[path]);}});return{root,calls,navigation,ui};}
test('Overview only reads current routes, displays exact pending counts and literal titles; destinations do not approve actions',async()=>{const h=harness();await h.ui.refresh();assert.match(h.root.textContent,/1 unread/);assert.match(h.root.textContent,/3 cards due/);assert.match(h.root.textContent,/1 AI task/);assert.match(h.root.textContent,/2 drafts/);assert.match(h.root.textContent,/<script>private focus<\/script>/);assert.equal(h.calls.every(call=>call.length===1),true);for(const card of h.root.children)card.children.at(-1).listeners.click();assert.deepEqual(h.navigation,['focus','reminders','practice','agents','writing']);});
test('Unavailable or malformed private data remains unknown instead of zero',async()=>{const h=harness(path=>{if(path==='/reminders/inbox')throw new Error('private error');if(path==='/practice/due')return null;return structuredClone(values[path]);});await h.ui.refresh();assert.equal(h.root.children.filter(card=>card.textContent.includes('Could not check')).length,2);assert.doesNotMatch(h.root.textContent,/private error|0 unread|0 cards/);});
test('Reset during an outstanding read removes private text and ignores all late results',async()=>{let release;const gate=new Promise(resolve=>release=resolve),h=harness(async path=>{await gate;return structuredClone(values[path]);});const pending=h.ui.refresh();h.ui.reset();release();await pending;assert.equal(h.root.children.length,0);});
test('Newest refresh wins and detached old controls cannot navigate after reset',async()=>{let release;const gate=new Promise(resolve=>release=resolve);let read=0;const h=harness(async path=>{const sequence=++read;if(sequence<=5)await gate;return path==='/practice/due'?{total_due:sequence<=5?7:2,unavailable:[]}:structuredClone(values[path]);});const old=h.ui.refresh();await h.ui.refresh();release();await old;assert.match(h.root.textContent,/2 cards due/);assert.doesNotMatch(h.root.textContent,/7 cards due/);const control=h.root.children[0].children.at(-1);h.ui.reset();control.listeners.click();assert.deepEqual(h.navigation,[]);});
