import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Database from 'better-sqlite3';
import { startRuntime } from '../apps/local-runtime/src/server.mjs';
import { mountStudentAdminUI } from '../apps/local/public/student-admin.js';
async function fixture(t) { const root = await mkdtemp(join(tmpdir(), 'learnbridge-admin-http-')), runtimes = []; t.after(async () => { for (const runtime of runtimes.reverse()) await runtime.close(); await rm(root, { recursive: true, force: true }); }); async function start() { const runtime = await startRuntime({ dataRoot: root, port: 0 }); runtimes.push(runtime); return runtime; } return { root, start, runtime: await start() }; }
async function pair(runtime) { const response = await fetch(`${runtime.origin}/api/local/v1/pair`, { method: 'POST', headers: { Origin: runtime.origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ code: runtime.createPairingCode() }) }); assert.equal(response.status, 200); return { cookie: response.headers.get('set-cookie').split(';')[0], nonce: (await response.json()).nonce }; }
async function call(runtime, session, path, { method = 'GET', body, origin = runtime.origin, headers = {} } = {}) { const response = await fetch(`${runtime.origin}/api/local/v1${path}`, { method, headers: { ...(session ? { Cookie: session.cookie, 'X-LearnBridge-Nonce': session.nonce } : {}), ...(method === 'GET' ? {} : { Origin: origin, 'Content-Type': 'application/json' }), ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); return { status: response.status, cache: response.headers.get('cache-control'), data: await response.json() }; }
const input = (patch = {}) => ({ title: 'Synthetic administration requirement', category: 'school', official_url: 'https://university.edu/student-forms', source_text: 'Provide a confirmed enrollment statement. Deadline October 10. PRIVATE_ADMIN_HTTP_CANARY', checked_at: '2026-10-01T15:00:00.000Z', timezone: 'America/Toronto', deadline: { precision: 'date', date: '2026-10-10', original: 'Deadline October 10.' }, requirements: [{ key: 'enrollment', excerpt: 'Provide a confirmed enrollment statement.', status: 'unknown', review_note: 'I still need to obtain this statement.', profile_fact_ids: [] }], checklist: [], ...patch });
async function create(runtime, session, value = input()) { const result = await call(runtime, session, '/student-admin/items', { method: 'POST', body: value, headers: { 'Idempotency-Key': 'student-admin-http-create' } }); assert.equal(result.status, 201, JSON.stringify(result.data)); return result.data.item; }
async function prepare(runtime, session, row, key = 'student-admin-http-prepare') { const result = await call(runtime, session, `/student-admin/items/${row.id}/prepare`, { method: 'POST', body: { expected_revision: row.revision, item_hash: row.data.item_hash }, headers: { 'Idempotency-Key': key } }); assert.equal(result.status, 201, JSON.stringify(result.data)); return result.data.item; }
const review = row => ({ expected_revision: row.revision, review_hash: row.data.review_hash, confirmed: true });
test('SAHTTP01: real paired HTTP record→preview→human task acceptance survives restart, appears in Today and does not contaminate study plans or travel', async t => {
  const f = await fixture(t); let runtime = f.runtime, session = await pair(runtime); const row = await create(runtime, session), preview = await prepare(runtime, session, row); assert.equal((await call(runtime, session, '/tasks')).data.items.length, 0); assert.equal((await call(runtime, session, '/plans')).data.items.length, 0);
  const wrongPlan = await call(runtime, session, `/plans/${preview.id}/accept`, { method: 'POST', body: { expected_revision: preview.revision, plan_hash: preview.data.review_hash } }); assert.equal(wrongPlan.status, 409);
  const accepted = await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview) }); assert.equal(accepted.status, 200, JSON.stringify(accepted.data)); const taskId = accepted.data.item.data.task_id;
  assert.equal((await call(runtime, session, '/tasks')).data.items.length, 1); assert.equal((await call(runtime, session, '/life/travel')).data.items.length, 0); assert.equal((await call(runtime, session, '/agent-grants')).data.items.length, 0);
  const today = await call(runtime, session, '/today'); assert.match(JSON.stringify(today.data), new RegExp(taskId)); assert.equal((await call(runtime, session, '/student-admin/items')).cache, 'private, no-store');
  await runtime.close(); runtime = await f.start(); session = await pair(runtime); const replay = await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview) }); assert.equal(replay.status, 200); assert.equal(replay.data.item.data.task_id, taskId); assert.equal((await call(runtime, session, '/tasks')).data.items.length, 1); assert.equal((await call(runtime, session, `/student-admin/items/${row.id}`)).data.item.data.linked_task_id, taskId);
});
test('SAHTTP02: actual source correction and profile-purpose/revision gates invalidate prior acceptance without creating tasks', async t => {
  const f = await fixture(t), runtime = f.runtime, session = await pair(runtime), candidate = (await call(runtime, session, '/profile', { method: 'POST', body: { field: 'goals', value: 'Plan student funding' } })).data.fact;
  let current = (await call(runtime, session, '/profile')).data.items.find(row => row.id === candidate.id); const fact = await call(runtime, session, `/profile/${current.id}/review`, { method: 'POST', body: { expected_revision: current.revision, decision: 'confirm', fingerprint: current.fingerprint } }); assert.equal(fact.status, 200);
  const row = await create(runtime, session, input({ requirements: [{ ...input().requirements[0], profile_fact_ids: [candidate.id] }] })), preview = await prepare(runtime, session, row); current = (await call(runtime, session, '/profile')).data.items.find(row => row.id === candidate.id);
  assert.equal((await call(runtime, session, `/profile/${current.id}/review`, { method: 'POST', body: { expected_revision: current.revision, decision: 'correct', fingerprint: current.fingerprint, value: 'Changed reviewed goal' } })).status, 200);
  assert.equal((await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview) })).status, 409); assert.equal((await call(runtime, session, `/student-admin/items/${row.id}`)).data.item.profile_stale, true);
  const correction = await call(runtime, session, `/student-admin/items/${row.id}`, { method: 'POST', body: { expected_revision: row.revision, item_hash: row.data.item_hash, definition: input({ title: 'Corrected source record' }), confirmed: true } }); assert.equal(correction.status, 200);
  assert.equal((await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview) })).status, 409); assert.equal((await call(runtime, session, '/tasks')).data.items.length, 0);
});
test('SAHTTP03: actual session/origin/nonce/query/schema/consent guards cannot read websites, submit forms or create tasks', async t => {
  const f = await fixture(t), runtime = f.runtime; assert.equal((await call(runtime, null, '/student-admin/context')).status, 401); const session = await pair(runtime), row = await create(runtime, session), preview = await prepare(runtime, session, row);
  assert.equal((await call(runtime, { ...session, nonce: 'forged' }, '/student-admin/items')).status, 403); assert.equal((await call(runtime, session, '/student-admin/items?token=PRIVATE_QUERY_CANARY')).status, 400);
  assert.equal((await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview), origin: 'https://hostile.invalid' })).status, 403);
  for (const [body, status] of [[{ ...review(preview), confirmed: false }, 403], [{ ...review(preview), review_hash: 'a'.repeat(64) }, 409], [{ ...review(preview), submit_form: true }, 400]]) assert.equal((await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body })).status, status);
  for (const path of ['/student-admin/fetch-url', '/student-admin/submit-form', '/student-admin/calendar-write', '/student-admin/profile-discovery']) assert.equal((await call(runtime, session, path, { method: 'POST', body: {} })).status, 404);
  assert.equal((await call(runtime, session, '/student-admin/items', { method: 'POST', body: input({ official_url: 'https://university.edu/forms?access_token=PRIVATE_SECRET_CANARY' }), headers: { 'Idempotency-Key': 'student-admin-http-secret' } })).status, 400); assert.equal((await call(runtime, session, '/tasks')).data.items.length, 0);
  assert.equal((await call(runtime, session, '/logout', { method: 'POST', body: {} })).status, 200); assert.equal((await call(runtime, session, '/student-admin/previews')).status, 401);
});
test('SAHTTP04: actual SQLite finalization failure returns no completion claim; restart exact journal replay recovers one unchanged existing task', async t => {
  const f = await fixture(t); let runtime = f.runtime, session = await pair(runtime); const row = await create(runtime, session), preview = await prepare(runtime, session, row), db = new Database(join(f.root, 'learnbridge.sqlite'));
  db.exec(`CREATE TRIGGER fail_admin_finalize BEFORE UPDATE ON workspace_records WHEN NEW.id='${preview.id}' AND NEW.json LIKE '%"state":"accepted"%' BEGIN SELECT RAISE(ABORT,'fixture finalization failure'); END;`);
  const result = await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview) }); assert.equal(result.status, 500); const tasks = (await call(runtime, session, '/tasks')).data.items; assert.equal(tasks.length, 1); assert.equal((await call(runtime, session, `/student-admin/previews/${preview.id}`)).data.item.data.state, 'accepting'); assert.equal((await call(runtime, session, `/student-admin/items/${row.id}`)).data.item.data.linked_task_id, null);
  assert.equal((await call(runtime, session, `/student-admin/previews/${preview.id}/cancel`, { method: 'POST', body: review(preview) })).status, 403); await runtime.close(); db.exec('DROP TRIGGER fail_admin_finalize'); db.close(); runtime = await f.start(); session = await pair(runtime);
  const recovered = await call(runtime, session, `/student-admin/previews/${preview.id}/accept`, { method: 'POST', body: review(preview) }); assert.equal(recovered.status, 200); assert.equal(recovered.data.item.data.task_id, tasks[0].id); assert.deepEqual((await call(runtime, session, '/tasks')).data.items, tasks);
});
class Node { constructor(tag, cls = '', text = '') { this.tagName = tag; this.className = cls; this.text = text; this.children = []; this.listeners = new Map(); this.value = ''; this.checked = false; this.disabled = false; this.classList = { toggle() {} }; } append(...nodes) { this.children.push(...nodes); } replaceChildren(...nodes) { this.children = nodes; this.text = ''; } addEventListener(type, callback) { this.listeners.set(type, [...(this.listeners.get(type) || []), callback]); } setAttribute() {} get textContent() { return this.text + this.children.map(node => node.textContent).join(''); } set textContent(value) { this.text = String(value); this.children = []; } }
const walk = node => [node, ...node.children.flatMap(walk)];
test('SAHTTP05: shipped dashboard controller uses actual paired HTTP save→preview→accept with literal pasted evidence and zero automatic task acceptance', async t => {
  const f = await fixture(t), runtime = f.runtime, session = await pair(runtime), root = new Node('main'), jobs = [], requests = [], confirmations = [];
  const asset = await fetch(`${runtime.origin}/student-admin.js`); assert.equal(asset.status, 200); assert.match(await asset.text(), /mountStudentAdminUI/);
  const ui = mountStudentAdminUI({ root, element: (tag, cls, text) => new Node(tag, cls, text), request: async (path, extra = {}) => { requests.push({ path, ...extra }); const result = await call(runtime, session, path, { ...extra, headers: { ...(extra.idempotencyKey ? { 'Idempotency-Key': extra.idempotencyKey } : {}) } }); assert(result.status < 400, JSON.stringify(result.data)); return result.data; }, busy(target, action) { target.disabled = true; const job = Promise.resolve().then(action).finally(() => { target.disabled = false; }); jobs.push(job); return job; }, confirmAction: async text => { confirmations.push(text); return true; } }); t.after(() => ui.reset());
  const find = predicate => { const node = walk(root).find(predicate); assert(node); return node; }, input = id => find(node => node.id === id), click = async text => { const node = find(node => node.tagName === 'button' && node.textContent === text); for (const listener of node.listeners.get('click') || []) listener({ preventDefault() {} }); await jobs.at(-1); };
  await ui.refresh(); for (const [key, value] of Object.entries({ title: 'Controller scholarship', url: 'https://university.edu/awards/controller', source: 'Provide enrollment statement. PRIVATE_CONTROLLER_SOURCE_CANARY', 'checked-at': '2026-10-01T15:00:00.000Z', timezone: 'America/Toronto', 'requirement_1-excerpt': 'Provide enrollment statement.' })) input(`student-admin-${key}`).value = value;
  const form = find(node => node.tagName === 'form'); for (const listener of form.listeners.get('submit') || []) listener({ preventDefault() {} }); await jobs.at(-1); assert.equal((await call(runtime, session, '/tasks')).data.items.length, 0);
  await click('Prepare a local task preview'); assert.equal((await call(runtime, session, '/tasks')).data.items.length, 0); await click('Review and add this local task'); const task = (await call(runtime, session, '/tasks')).data.items[0]; assert.equal(task.title, 'Review requirements: Controller scholarship'); assert.equal(task.deadline.precision, 'unknown'); assert.equal(confirmations.length, 2); assert.equal(requests.filter(row => row.path.endsWith('/accept')).length, 1); assert.match(root.textContent, /PRIVATE_CONTROLLER_SOURCE_CANARY/); assert.equal((await call(runtime, session, '/agent-grants')).data.items.length, 0);
});
