import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {startRuntime} from '../apps/local-runtime/src/server.mjs';
import {LocalStore} from '../packages/local-storage/src/index.mjs';
async function fixture(t){const base=await mkdtemp(join(tmpdir(),'learnbridge-calendar-import-http-')),root=join(base,'private'),runtimes=[];t.after(async()=>{for(const runtime of runtimes.reverse())await runtime.close();await rm(base,{recursive:true,force:true});});async function start(dataRoot=root){const runtime=await startRuntime({dataRoot,port:0});runtimes.push(runtime);return runtime;}return{base,root,start,runtime:await start()};}
async function pair(runtime){const response=await fetch(`${runtime.origin}/api/local/v1/pair`,{method:'POST',headers:{Origin:runtime.origin,'Content-Type':'application/json'},body:JSON.stringify({code:runtime.createPairingCode()})});assert.equal(response.status,200);return{cookie:response.headers.get('set-cookie').split(';')[0],nonce:(await response.json()).nonce};}
async function call(runtime,session,path,{method='GET',body,key,origin=runtime.origin}={}){const response=await fetch(`${runtime.origin}/api/local/v1${path}`,{method,headers:{...(session?{Cookie:session.cookie,'X-LearnBridge-Nonce':session.nonce}:{}),...(method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'}),...(key?{'Idempotency-Key':key}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,data:await response.json(),cache:response.headers.get('cache-control')};}
function content(){const first=Math.ceil((Date.now()+86400000)/3600000)*3600000,start=new Date(first).toISOString(),end=new Date(first+4*3600000).toISOString(),time=at=>new Date(at).toISOString().replace(/[-:]/g,'').replace('.000Z','Z');return{scope:{start,end},filename:'selected-http.ics',timezone:'UTC',content:`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Synthetic//EN\r\nBEGIN:VEVENT\r\nUID:busy\r\nDTSTAMP:${time(Date.now()-Date.now()%1000)}\r\nDTSTART:${time(first+3600000)}\r\nDTEND:${time(first+2*3600000)}\r\nSUMMARY:<script>BUSY_LITERAL</script>\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:unselected\r\nDTSTART:${time(first+2*3600000)}\r\nDTEND:${time(first+3*3600000)}\r\nSUMMARY:UNCHECKED_CALENDAR_PRIVATE_CANARY\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`};}
async function create(t){const f=await fixture(t),session=await pair(f.runtime),raw=content(),{scope,...body}=raw,response=await call(f.runtime,session,'/calendar-import/previews',{method:'POST',body,key:'http-calendar-preview'});assert.equal(response.status,201,JSON.stringify(response.data));const row=response.data.item,review={expected_revision:row.revision,review_hash:row.data.review_hash,selected_indexes:[0],scope,confirmed:true};return{...f,session,raw,row,review};}

test('CIHTTP01: actual paired file preview→selected busy acceptance→concurrent replay→restart→fresh backup restore retains exact private source',async t=>{
  const f=await create(t);let runtime=f.runtime,session=f.session;assert.match((await call(runtime,session,'/calendar-import/previews')).cache,/private, no-store/);assert.equal((await call(runtime,session,'/calendar-import/sources')).data.items.length,0);
  const results=await Promise.all([1,2].map(()=>call(runtime,session,`/calendar-import/previews/${f.row.id}/accept`,{method:'POST',body:f.review,key:'http-calendar-accept'})));assert.deepEqual(results.map(r=>r.status),[200,200]);assert.equal(results[0].data.source.id,results[1].data.source.id);const saved=results[0].data.source;assert.doesNotMatch(JSON.stringify(saved),/UNCHECKED_CALENDAR_PRIVATE_CANARY/);assert.equal((await call(runtime,session,'/calendar-import/sources')).data.items.length,1);assert.equal((await call(runtime,session,'/tasks')).data.items.length,0);
  await runtime.close();runtime=await f.start();session=await pair(runtime);assert.deepEqual((await call(runtime,session,'/calendar-import/sources')).data.items[0],saved);assert.equal((await call(runtime,session,`/calendar-import/previews/${f.row.id}/accept`,{method:'POST',body:f.review,key:'http-calendar-accept'})).data.outcome,'replayed');
  await runtime.close();const store=LocalStore.open({root:f.root});try{await store.backup(join(f.base,'backup'));}finally{store.close();}const restored=join(f.base,'restored');await LocalStore.restore({backupRoot:join(f.base,'backup'),root:restored});runtime=await f.start(restored);session=await pair(runtime);assert.deepEqual((await call(runtime,session,'/calendar-import/sources')).data.items[0],saved);assert.equal((await call(runtime,session,'/calendar-import/previews')).data.items[0].data.request.content,f.raw.content);
});
test('CIHTTP02: actual workflow avoids checked busy times, accepts exact plan, exports saved blocks and refuses forgotten source on all retries',async t=>{
  const f=await create(t),{runtime,session}=f,source=(await call(runtime,session,`/calendar-import/previews/${f.row.id}/accept`,{method:'POST',body:f.review,key:'http-calendar-accept'})).data.source;
  const task=await call(runtime,session,'/tasks',{method:'POST',body:{title:'Synthetic study task',effort_minutes:90,deadline:{precision:'instant',instant:f.raw.scope.end}},key:'http-calendar-study-task'});assert.equal(task.status,201);
  const body={calendar_source:source.source_pin,availability:[f.raw.scope],timezone:'UTC',horizonEnd:f.raw.scope.end,maxDailyMinutes:240,bufferMinutes:0,minBlockMinutes:25};const response=await call(runtime,session,'/calendar-import/plans',{method:'POST',body,key:'http-calendar-study-plan'});assert.equal(response.status,201,JSON.stringify(response.data));assert.equal(response.data.run.state,'completed');const saved=response.data.plan;assert(saved.data.plan.blocks.length);for(const block of saved.data.plan.blocks)assert(!source.data.busy.some(b=>block.start<b.end&&block.end>b.start));
  const accepted=await call(runtime,session,`/plans/${saved.id}/accept`,{method:'POST',body:{expected_revision:1,plan_hash:saved.data.plan.plan_hash}});assert.equal(accepted.status,200);const exported=await call(runtime,session,'/calendar-export/previews',{method:'POST',body:{mode:'study_plan',plan_id:saved.id,expected_revision:2,plan_hash:saved.data.plan.plan_hash},key:'http-calendar-study-export'});assert.equal(exported.status,201,JSON.stringify(exported.data));assert.doesNotMatch(exported.data.item.data.content,/UNCHECKED_CALENDAR_PRIVATE_CANARY|BUSY_LITERAL/);
  const forgot=await call(runtime,session,`/calendar-import/sources/${source.id}/forget`,{method:'POST',body:{expected_revision:1,version_hash:source.source_pin.version_hash,confirmed:true}});assert.equal(forgot.status,200);assert.equal((await call(runtime,session,'/calendar-import/sources')).data.items.length,0);
  assert.equal((await call(runtime,session,`/plans/${saved.id}/accept`,{method:'POST',body:{expected_revision:2,plan_hash:saved.data.plan.plan_hash}})).status,409);assert.equal((await call(runtime,session,`/calendar-import/previews/${f.row.id}/accept`,{method:'POST',body:f.review,key:'http-calendar-accept'})).status,409);assert.equal((await call(runtime,session,`/calendar-export/previews/${exported.data.item.id}/download`,{method:'POST',body:{expected_revision:1,review_hash:exported.data.item.data.review_hash,confirmed:true}})).status,409);assert.equal((await call(runtime,session,'/tasks')).data.items.length,1);
});
test('CIHTTP03: actual auth/origin/nonce/query/schema/file/hash/consent gates deny unintended effects and zero-window planning',async t=>{
  const f=await fixture(t),runtime=f.runtime;assert.equal((await call(runtime,null,'/calendar-import/sources')).status,401);const session=await pair(runtime);assert.equal((await call(runtime,{...session,nonce:'wrong'},'/calendar-import/sources')).status,403);assert.equal((await call(runtime,session,'/calendar-import/previews',{method:'POST',body:{},origin:'https://hostile.invalid'})).status,403);assert.equal((await call(runtime,session,'/calendar-import/previews?cookie=PRIVATE_CANARY')).status,400);
  for(const body of [{filename:'https://evil.invalid/file.ics',content:'x',timezone:'UTC'},{filename:'a.ics',content:'x',timezone:'UTC',cookie:'PRIVATE'},{filename:'a.ics',content:'x'.repeat(48001),timezone:'UTC'}])assert([400,413].includes((await call(runtime,session,'/calendar-import/previews',{method:'POST',body,key:'http-bad-file'})).status));
  for(const path of ['/calendar-import/fetch-url','/calendar-import/send-calendar','/calendar-import/start-agent'])assert.equal((await call(runtime,session,path,{method:'POST',body:{}})).status,404);assert.equal((await call(runtime,session,'/calendar-import/previews')).data.items.length,0);assert.equal((await call(runtime,session,'/plans')).data.items.length,0);
  const raw=content(),recurrence={filename:'weekly.ics',timezone:'UTC',content:raw.content.replace('UID:busy','RRULE:FREQ=WEEKLY\r\nUID:busy').replace('UID:unselected','RRULE:FREQ=WEEKLY\r\nUID:unselected')},zero=await call(runtime,session,'/calendar-import/previews',{method:'POST',body:recurrence,key:'http-weekly-preview'});assert.equal(zero.status,201);assert.equal(zero.data.item.data.parsed.events.length,0);assert.equal((await call(runtime,session,`/calendar-import/previews/${zero.data.item.id}/accept`,{method:'POST',body:{expected_revision:1,review_hash:zero.data.item.data.review_hash,selected_indexes:[0],scope:raw.scope,confirmed:true},key:'http-weekly-accept'})).status,403);assert.equal((await call(runtime,session,'/calendar-import/sources')).data.items.length,0);
});
