import test from 'node:test';
import assert from 'node:assert/strict';
import { handleAdminDeadlineRoute } from '../apps/local-runtime/src/admin-deadline-routes.mjs';
const itemId = '01368fc2-631c-4220-824f-667d967ff9a7';
function fixture() { const calls = [], service = Object.fromEntries(['context', 'list', 'get', 'create', 'correct', 'prepare', 'listPreviews', 'getPreview', 'accept', 'cancel'].map(name => [name, (...args) => { calls.push({ name, args }); return ['list', 'listPreviews'].includes(name) ? [] : { id: itemId }; }])); return { calls, service, session: { nonce: 'synthetic' }, privateBody: async () => ({}), stillAuthorized() { calls.push({ name: 'authorize' }); } }; }
test('SAR01: exact paired administration routes forward only scoped local operations and idempotency keys', async () => { const f = fixture(); assert.equal(await handleAdminDeadlineRoute({ ...f, route: '/tasks', method: 'GET' }), null);
  for (const [route, method, name] of [['/student-admin/context', 'GET', 'context'], ['/student-admin/items', 'GET', 'list'], ['/student-admin/items', 'POST', 'create'], [`/student-admin/items/${itemId}`, 'GET', 'get'], [`/student-admin/items/${itemId}`, 'POST', 'correct'], [`/student-admin/items/${itemId}/prepare`, 'POST', 'prepare'], ['/student-admin/previews', 'GET', 'listPreviews'], [`/student-admin/previews/${itemId}`, 'GET', 'getPreview'], ...['accept', 'cancel'].map(op => [`/student-admin/previews/${itemId}/${op}`, 'POST', op])]) { const result = await handleAdminDeadlineRoute({ ...f, route, method, idempotencyKey: 'student-admin-route-key' }); assert.equal(result.status, ['create', 'prepare'].includes(name) ? 201 : 200); assert.equal(f.calls.at(-1).name, name); }
  assert.deepEqual(f.calls.find(call => call.name === 'create').args[1], { idempotencyKey: 'student-admin-route-key' }); assert.deepEqual(f.calls.find(call => call.name === 'prepare').args[2], { idempotencyKey: 'student-admin-route-key' });
});
test('SAR02: unauthenticated metadata and writes fail before service use', async () => { const f = fixture(); for (const session of [null, {}, { nonce: '' }, { nonce: 42 }]) await assert.rejects(handleAdminDeadlineRoute({ ...f, route: '/student-admin/context', method: 'GET', session }), { code: 'AUTH_REQUIRED' }); assert.equal(f.calls.length, 0); });
test('SAR03: session revoked during asynchronous body read cannot create, correct, accept or cancel', async () => { for (const route of ['/student-admin/items', `/student-admin/items/${itemId}`, `/student-admin/items/${itemId}/prepare`, `/student-admin/previews/${itemId}/accept`, `/student-admin/previews/${itemId}/cancel`]) { const f = fixture(); let authorized = true; f.stillAuthorized = () => { if (!authorized) { const e = new Error(); e.code = 'AUTH_REQUIRED'; throw e; } }; f.privateBody = async () => { authorized = false; return {}; }; await assert.rejects(handleAdminDeadlineRoute({ ...f, route, method: 'POST' }), { code: 'AUTH_REQUIRED' }); assert.equal(f.calls.length, 0); } });
test('SAR04: exact body allowlists and bounded reads exclude profile discovery, external submission and arbitrary task edits', async () => { const f = fixture(), bodies = []; f.privateBody = async (...args) => { bodies.push(args); return {}; };
  for (const route of ['/student-admin/items', `/student-admin/items/${itemId}`, `/student-admin/items/${itemId}/prepare`, `/student-admin/previews/${itemId}/accept`]) await handleAdminDeadlineRoute({ ...f, route, method: 'POST' });
  assert.deepEqual(bodies.map(call => call[0]), [['title', 'category', 'official_url', 'source_text', 'checked_at', 'timezone', 'deadline', 'requirements', 'checklist'], ['expected_revision', 'item_hash', 'definition', 'confirmed'], ['expected_revision', 'item_hash'], ['expected_revision', 'review_hash', 'confirmed']]); assert(bodies.every(call => call[2] === 64000 && JSON.stringify(call[0]) === JSON.stringify(call[1])));
});
test('SAR05: alternate namespaces/methods cannot submit forms, read websites, share profile data or overwrite accepted tasks', async () => { const f = fixture(); for (const route of ['/student-admin/fetch-url', '/student-admin/submit', `/student-admin/items/${itemId}/accept`, `/student-admin/previews/${itemId}/prepare`, `/student-admin/previews/${itemId}/edit-task`, '/student-admin/items/not-a-uuid']) await assert.rejects(handleAdminDeadlineRoute({ ...f, route, method: 'POST' }), { code: 'NOT_FOUND' }); for (const [route, method] of [['/student-admin/context', 'POST'], ['/student-admin/items', 'PATCH'], ['/student-admin/previews', 'POST'], [`/student-admin/items/${itemId}/prepare`, 'GET']]) await assert.rejects(handleAdminDeadlineRoute({ ...f, route, method }), { code: 'METHOD_NOT_ALLOWED' }); assert.equal(f.calls.some(call => call.name !== 'authorize'), false); });
