import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { setTimeout as delay } from 'node:timers/promises';
import { LocalStore } from '../packages/local-storage/src/index.mjs';
import { createHostTurns } from '../apps/local-runtime/src/host-turns.mjs';
import { createCodingPracticeService, parseCodingPracticeOutput, CODING_DIMENSIONS } from '../apps/local-runtime/src/coding-practice-service.mjs';
import { handleCodingPracticeRoute } from '../apps/local-runtime/src/coding-practice-routes.mjs';

const sha = value => createHash('sha256').update(value).digest('hex');
const canonical = value => Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}` : JSON.stringify(value);
const hash = value => sha(canonical(value));
const review = row => ({ expected_revision: row.revision, context_hash: row.data.context_hash });
const wrap = payload => `Practice only.\nBEGIN_LEARNBRIDGE_CODING\n${JSON.stringify(payload)}\nEND_LEARNBRIDGE_CODING`;
const question = problemId => ({ kind: 'question', message: 'How would you avoid checking the same pair twice?', follow_up: 'Explain which values must be remembered.', source_refs: [problemId] });
const hint = problemId => ({ kind: 'hint', message: 'Consider the value that would complete the target.', follow_up: 'Which lookup operation could help?', source_refs: [problemId] });
const feedback = (problemId, quote = 'I compare pairs.') => ({ kind: 'review', summary: 'The checkpoint explains a pair comparison; tests and correctness remain unverified.', evidence: CODING_DIMENSIONS.map(dimension => ({ dimension, assessment: dimension === 'approach' ? 'observed' : 'not_assessed', evidence_quote: dimension === 'approach' ? quote : '', evidence_from: dimension === 'approach' ? 'explanation' : 'none', reason: 'This describes the saved reasoning only.' })), next_question: 'What changes if the input contains duplicate values?', source_refs: [problemId] });
const result = payload => { const text = wrap(payload); return { state: 'completed', complete: true, text, output_sha256: sha(text), host_version: 'fixture-not-live', error_code: null, tool_receipts: [{ tool: 'learnbridge_context', status: 'completed', failed: false, result_hash: sha('fixture context'), origin: 'model' }] }; };

function fixture(t, { executor, enabled = true, content = 'Find two distinct indices whose values sum to the target.' } = {}) {
  const parent = mkdtempSync(join(tmpdir(), 'learnbridge-coding-practice-')), root = join(parent, 'private'); let store = LocalStore.open({ root }), calls = 0, allowed = true, clockMs = Date.now();
  const selected = store.createWorkspaceRecord({ kind: 'career_item', title: 'Two Sum fixture', data: { format: 'learnbridge_leetcode_problem.v1', slug: 'two-sum', title: 'Two Sum fixture', difficulty: 'Easy', tags: ['Array', 'Hash Table'], content, code_snippets: [{ lang: 'Python3', lang_slug: 'python3', code: 'class Solution:\n    pass\n' }], example_testcases: '[2,7,11,15]\n9', is_paid_only: false, url: 'https://leetcode.com/problems/two-sum/', observed_at: new Date(clockMs).toISOString(), account_username: 'fixture-student' } });
  const unselected = store.createDocument({ title: 'Private unrelated', text: 'UNSELECTED_CODING_PRACTICE_CANARY' });
  const leetcode = { problem: recordId => { const row = store.getWorkspaceRecord(recordId); if (!row || row.data.format !== 'learnbridge_leetcode_problem.v1') throw Error('Not a saved problem'); return { ...row, sha256: hash(row.data) }; }, submission: recordId => { const row = store.getWorkspaceRecord(recordId); if (!row || row.data.format !== 'learnbridge_leetcode_submission.v1') throw Error('Not a saved report'); return { ...row, sha256: hash(row.data) }; }, problems: () => store.listWorkspaceRecords({ kind: 'career_item' }).filter(row => row.data.format === 'learnbridge_leetcode_problem.v1').map(row => ({ ...row, sha256: hash(row.data) })) };
  const createReport = (overrides = {}) => { const row = store.createWorkspaceRecord({ kind: 'career_item', title: 'Selected historical answer fixture', data: { format: 'learnbridge_leetcode_submission.v1', username: 'fixture-student', submission_id: '12345', slug: 'two-sum', title: 'Two Sum fixture', code: '  def pair(values):\n    return values[0] + values[1]\n', language: 'python3', status_code: 11, runtime: '20 ms', memory: '16 MB', runtime_percentile: null, memory_percentile: null, total_correct: 4, total_testcases: 20, timestamp: new Date(clockMs - 100000).toISOString(), observed_at: new Date(clockMs).toISOString(), url: 'https://leetcode.com/submissions/detail/12345/', correctness: 'platform_reported_not_locally_executed', ...overrides } }); return { ...row, sha256: hash(row.data) }; };
  function hosts() { return createHostTurns({ store, enabled, execute: async input => {
    calls++; assert.equal(input.toolPolicy, 'read_only'); const selectedContext = store.agentContext({ destination: 'codex', grant_id: input.grantId, max_bytes: 32000 }); assert.equal(selectedContext.documents.length, 1); assert.deepEqual(selectedContext.tasks, []); assert.equal(JSON.stringify(selectedContext).includes('UNSELECTED_CODING_PRACTICE_CANARY'), false); assert.ok(selectedContext.serialized_bytes <= 32000);
    input.onProgress({ phase: 'tool', tool: 'learnbridge_context', state: 'finished' }); if (executor) return executor(input, { problem: selected, context: JSON.parse(selectedContext.documents[0].text) });
    return result(input.prompt.includes('Requested kind: review.') ? feedback(selected.id) : input.prompt.includes('Requested kind: hint.') ? hint(selected.id) : question(selected.id));
  } }); }
  let hostTurns = hosts(), service = createCodingPracticeService({ store, hostTurns, leetcodeService: leetcode, clock: () => clockMs });
  t.after(async () => { await hostTurns.drain(); store.close(); rmSync(parent, { recursive: true, force: true }); });
  const input = () => { const problem = leetcode.problem(selected.id); return { problem_ref: { id: problem.id, revision: problem.revision, sha256: problem.sha256 }, language: 'python3', mode: 'practice' }; };
  const create = (overrides = {}) => service.create({ ...input(), ...overrides }, { idempotencyKey: randomUUID() });
  const checkpoint = (row, code = 'def pair(values):\n    return values[0] + values[1]\n', explanation = 'I compare pairs.') => service.checkpoint(row.id, { ...review(row), code, explanation });
  const exportAndGrant = row => { row = service.exportContext(row.id, review(row)); const grant = store.createAgentGrant({ destination: 'codex', task_ids: [], document_ids: [row.data.context_note.id], source_entry_ids: [], max_bytes: 256000, expires_in_minutes: 10 }); return { row, grant }; };
  async function run(row, grant, requestKind = 'question', idempotencyKey = randomUUID()) { const preview = service.previewRun(row.id, { ...review(row), kind: requestKind }); return service.run(row.id, { ...review(row), kind: requestKind, grant_id: grant.id, prompt_sha256: preview.prompt_sha256, confirmed: true }, { idempotencyKey, authorize: () => allowed }); }
  async function settled(row) { for (let n = 0; n < 100; n++) { const current = service.get(row.id); if (current.data.pending?.state !== 'running') return current; await delay(5); } throw Error('Fixture host did not settle'); }
  async function reopen(restore = false) { let target = root; if (restore) { const backupRoot = join(parent, 'backup'); await store.backup(backupRoot); await hostTurns.drain(); store.close(); target = join(parent, 'restored'); await LocalStore.restore({ backupRoot, root: target }); } else { await hostTurns.drain(); store.close(); } store = LocalStore.open({ root: target }); hostTurns = createHostTurns({ store, enabled, execute: async () => { throw Error('No restart replay'); } }); service = createCodingPracticeService({ store, hostTurns, leetcodeService: leetcode, clock: () => clockMs }); }
  return { parent, root, selected, unselected, leetcode, input, create, createReport, checkpoint, exportAndGrant, run, settled, reopen, setAllowed: value => { allowed = value; }, advance: ms => { clockMs += ms; }, get calls() { return calls; }, get service() { return service; }, get store() { return store; }, get hosts() { return hostTurns; } };
}

test('CP01 session pins one saved problem/language and creates no grants, model turns, tasks or private-context reads', t => {
  const f = fixture(t), before = { docs: f.store.listDocuments(), grants: f.store.listAgentGrants(), tasks: f.store.listTasks() }, row = f.service.create(f.input(), { idempotencyKey: 'coding-create-fixed' });
  assert.equal(row.data.context.problem.id, f.selected.id); assert.equal(row.data.context.problem.starter.lang_slug, 'python3'); assert.equal(row.data.checkpoint_refs.length, 0); assert.equal(row.code_execution_verified, false); assert.equal(row.skill_score, null); assert.equal(row.automatic_submission, false); assert.equal(f.calls, 0); assert.equal(JSON.stringify(row).includes('UNSELECTED_CODING_PRACTICE_CANARY'), false); assert.deepEqual({ docs: f.store.listDocuments(), grants: f.store.listAgentGrants(), tasks: f.store.listTasks() }, before);
  assert.equal(f.service.create(f.input(), { idempotencyKey: 'coding-create-fixed' }).id, row.id); assert.throws(() => f.service.create({ ...f.input(), mode: 'mock_interview' }, { idempotencyKey: 'coding-create-fixed' }), { code: 'REVISION_CONFLICT' }); assert.throws(() => f.create({ language: 'shell' }), { code: 'UNSUPPORTED' });
});

test('CP02 distinct checkpoints preserve literal code/explanation and require fresh context export/sharing', t => {
  const f = fixture(t); let row = f.create(), firstHash = row.data.context_hash; f.advance(1500); row = f.checkpoint(row, '  print("hello")\n', '  I compare pairs.  '); assert.equal(row.checkpoints[0].data.code, '  print("hello")\n'); assert.equal(row.checkpoints[0].data.explanation, '  I compare pairs.  '); assert.equal(row.checkpoints[0].data.elapsed_ms, 1500); assert.notEqual(row.data.context_hash, firstHash); assert.equal(row.data.context_note, null);
  const exported = f.exportAndGrant(row); row = f.checkpoint(exported.row, '  print("hello")\n', '  I compare pairs.  '); assert.equal(row.checkpoints.length, 2); assert.notEqual(row.checkpoints[0].id, row.checkpoints[1].id); assert.equal(row.data.context_note, null); assert.equal(row.data.context.checkpoint.id, row.checkpoints[1].id); assert.equal(f.calls, 0); assert.equal(f.store.listAgentGrants().length, 1);
  assert.throws(() => f.service.checkpoint(row.id, { ...review(exported.row), code: 'replace', explanation: '' }), { code: 'REVISION_CONFLICT' }); assert.throws(() => f.checkpoint(row, '', ''), { code: 'INVALID_INPUT' });
});

test('CP03 exact bounded note contains current problem/checkpoint only and broad or wrong-destination grants never execute', async t => {
  const f = fixture(t), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())); assert.deepEqual(JSON.parse(f.store.getDocument(row.data.context_note.id).text), row.data.context); assert.equal(f.service.exportContext(row.id, review(row)).revision, row.revision);
  const broad = f.store.createAgentGrant({ destination: 'codex', task_ids: [], document_ids: [row.data.context_note.id, f.unselected.document.id], source_entry_ids: [], max_bytes: 256000, expires_in_minutes: 10 }); await assert.rejects(f.run(row, broad), { code: 'SCOPE_DENIED' });
  const claude = f.store.createAgentGrant({ destination: 'claude', task_ids: [], document_ids: [row.data.context_note.id], source_entry_ids: [], max_bytes: 256000, expires_in_minutes: 10 }); await assert.rejects(f.run(row, claude), { code: 'SCOPE_DENIED' }); const empty = f.store.createAgentGrant({ destination: 'codex', task_ids: [], document_ids: [], source_entry_ids: [], max_bytes: 256000, expires_in_minutes: 10 }); await assert.rejects(f.run(row, empty), { code: 'SCOPE_DENIED' }); assert.equal(f.calls, 0); assert.equal(grant.pins.documents.length, 1);
});

test('CP04 reviewed question, hint and evidence feedback link to actual saved checkpoint and host receipts', async t => {
  const f = fixture(t), exported = f.exportAndGrant(f.checkpoint(f.create())); let row = await f.settled(await f.run(exported.row, exported.grant)); assert.equal(row.data.coaching[0].payload.kind, 'question'); assert.equal(row.data.coaching[0].checkpoint_id, row.checkpoints[0].id);
  row = await f.settled(await f.run(row, exported.grant, 'hint')); assert.equal(row.data.coaching[1].payload.kind, 'hint'); row = await f.settled(await f.run(row, exported.grant, 'review')); assert.equal(row.data.coaching[2].payload.evidence[0].evidence_quote, 'I compare pairs.'); assert.equal(row.data.coaching[2].origin.tool_receipts[0].origin, 'model'); assert.equal(f.hosts.get(row.data.coaching[2].origin.turn_id).data.tool_policy, 'read_only'); assert.equal(row.data.state, 'ready'); assert.equal(row.checkpoints[0].data.judge_outcome, null); assert.equal(f.calls, 3);
});

test('CP05 explicit exact prompt confirmation and request keys cannot execute edited code/phase or replay', async t => {
  const f = fixture(t), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())), preview = f.service.previewRun(row.id, { ...review(row), kind: 'review' }), input = { ...review(row), kind: 'review', grant_id: grant.id, prompt_sha256: preview.prompt_sha256, confirmed: true }, options = { idempotencyKey: 'coding-one-request', authorize: () => true };
  await assert.rejects(f.service.run(row.id, { ...input, confirmed: false }, options), { code: 'INVALID_INPUT' }); await assert.rejects(f.service.run(row.id, { ...input, prompt_sha256: sha('changed') }, options), { code: 'REVISION_CONFLICT' }); await assert.rejects(f.service.run(row.id, { ...input, submit: true }, options), { code: 'INVALID_INPUT' });
  const started = await f.service.run(row.id, input, options), saved = await f.settled(started), retry = await f.service.run(row.id, input, options); assert.equal(retry.data.pending.turn_id, saved.data.pending.turn_id); assert.equal(f.calls, 1); await assert.rejects(f.service.run(row.id, { ...input, kind: 'hint' }, options), { code: 'REVISION_CONFLICT' });
});

test('CP06 model parser requires exact evidence provenance, one envelope and selected source; no scores/correctness extras', t => {
  const problemId = randomUUID(), good = feedback(problemId); assert.deepEqual(parseCodingPracticeOutput(wrap(good), { requestKind: 'review', problemId, explanation: 'I compare pairs.' }), good);
  const forged = structuredClone(good); forged.evidence[0].evidence_quote = 'All tests passed.'; assert.throws(() => parseCodingPracticeOutput(wrap(forged), { requestKind: 'review', problemId, explanation: 'I compare pairs.' }), { code: 'VERSION_MISMATCH' });
  const source = structuredClone(good); source.evidence[0].evidence_from = 'code'; assert.throws(() => parseCodingPracticeOutput(wrap(source), { requestKind: 'review', problemId, code: 'return 1', explanation: 'I compare pairs.' }), { code: 'VERSION_MISMATCH' });
  const unsupported = structuredClone(good); unsupported.evidence.forEach(row => { row.assessment = 'reviewed'; }); assert.throws(() => parseCodingPracticeOutput(wrap(unsupported), { requestKind: 'review', problemId, explanation: 'I compare pairs.' }), { code: 'VERSION_MISMATCH' });
  for (const payload of [{ ...good, score: 100 }, { ...good, correct: true }, { ...question(problemId), source_refs: [randomUUID()] }]) assert.throws(() => parseCodingPracticeOutput(wrap(payload), { requestKind: payload.kind, problemId, explanation: 'I compare pairs.' }));
  assert.throws(() => parseCodingPracticeOutput(wrap(good) + wrap(good), { requestKind: 'review', problemId, explanation: 'I compare pairs.' }), { code: 'VERSION_MISMATCH' }); assert.throws(() => parseCodingPracticeOutput('You mastered this topic.', { requestKind: 'question', problemId }), { code: 'VERSION_MISMATCH' });
});

test('CP07 source change withholds model output while preserving the student actual code/explanation', async t => {
  const f = fixture(t), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())), saved = await f.settled(await f.run(row, grant, 'review')); f.store.updateWorkspaceRecord(f.selected.id, { expected_revision: f.selected.revision, data: { ...f.selected.data, content: 'A changed source statement.' } });
  const hidden = f.service.get(saved.id); assert.equal(hidden.stale, true); assert.equal(hidden.data.context, null); assert.equal(hidden.data.coaching[0].payload, null); assert.equal(hidden.checkpoints[0].data.code, saved.checkpoints[0].data.code); assert.throws(() => f.service.previewRun(hidden.id, { ...review(hidden), kind: 'question' }), { code: 'REVISION_CONFLICT' });
});

test('CP08 edited context note and forged checkpoint prevent future use and cached coaching exposure', async t => {
  for (const mutation of ['note', 'checkpoint']) { const f = fixture(t), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())), saved = await f.settled(await f.run(row, grant)); if (mutation === 'note') { const note = f.store.getDocument(row.data.context_note.id); f.store.updateDocument(note.document.id, { text: 'Changed context.' }, note.document.revision); } else { const checkpoint = saved.checkpoints[0]; f.store.updateWorkspaceRecord(checkpoint.id, { expected_revision: checkpoint.revision, data: { ...checkpoint.data, code: 'forged code' } }); } const hidden = f.service.get(saved.id); assert.equal(hidden.stale, true); assert.equal(hidden.data.coaching[0].payload, null); assert.throws(() => f.service.previewRun(hidden.id, { ...review(hidden), kind: 'hint' })); }
});

test('CP09 new checkpoint creates a new exact grant context while old coaching honors its own original grant', async t => {
  const f = fixture(t), initial = f.exportAndGrant(f.checkpoint(f.create())); let row = await f.settled(await f.run(initial.row, initial.grant, 'review')); row = f.checkpoint(row, 'return values[0]', 'I compare pairs.'); assert.equal(row.data.coaching[0].payload.kind, 'review'); const second = f.exportAndGrant(row); assert.notEqual(second.row.data.context_note.id, initial.row.data.context_note.id); await assert.rejects(f.run(second.row, initial.grant), { code: 'SCOPE_DENIED' }); const revoked = f.store.getAgentGrant(initial.grant.id); f.store.revokeAgentGrant(revoked.id, revoked.revision); row = f.service.get(row.id); assert.equal(row.data.coaching[0].payload, null); assert.equal(row.checkpoints.length, 2); assert.equal(row.checkpoints[1].data.code, 'return values[0]');
});

test('CP10 practice timer pauses/resumes, finished stays immutable and duration is never an ability score', t => {
  const f = fixture(t); let row = f.create({ mode: 'mock_interview' }); f.advance(2000); row = f.service.transition(row.id, { ...review(row), action: 'pause' }); assert.equal(row.elapsed_ms, 2000); f.advance(8000); assert.equal(f.service.get(row.id).elapsed_ms, 2000); assert.throws(() => f.checkpoint(row), { code: 'REVISION_CONFLICT' }); row = f.service.transition(row.id, { ...review(row), action: 'resume' }); f.advance(1000); row = f.checkpoint(row); assert.equal(row.checkpoints[0].data.elapsed_ms, 3000); row = f.service.transition(row.id, { ...review(row), action: 'finish' }); f.advance(4000); assert.equal(f.service.get(row.id).elapsed_ms, 3000); assert.equal(row.skill_score, null); assert.throws(() => f.checkpoint(row), { code: 'REVISION_CONFLICT' });
});

test('CP11 pause interrupts a linked host run and late output never attaches or triggers a replay', async t => {
  let release; const f = fixture(t, { executor: async (_, { problem }) => new Promise(resolve => { release = () => resolve(result(question(problem.id))); }) }), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())); let running = await f.run(row, grant); await delay(5); running = f.service.get(running.id); const paused = f.service.transition(running.id, { ...review(running), action: 'pause' }); release(); await delay(15); const saved = f.service.get(paused.id); assert.equal(saved.data.pending.state, 'interrupted'); assert.equal(saved.data.coaching.length, 0); assert.equal(saved.checkpoints.length, 1); assert.equal(f.calls, 1); assert.equal(f.hosts.get(running.data.pending.turn_id).data.text, '');
});

test('CP12 revoked paired-browser authority or grant prevents late feedback attachment', async t => {
  for (const revoke of ['authority', 'grant']) { let release; const f = fixture(t, { executor: async (_, { problem }) => new Promise(resolve => { release = () => resolve(result(feedback(problem.id))); }) }), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())); const running = await f.run(row, grant, 'review'); await delay(5); if (revoke === 'authority') f.setAllowed(false); else { const active = f.store.getAgentGrant(grant.id); f.store.revokeAgentGrant(active.id, active.revision); } release(); const saved = await f.settled(running); assert.equal(saved.data.pending.state, 'withheld'); assert.equal(saved.data.coaching.length, 0); }
});

test('CP13 restart and fresh SQLite backup restore retain checkpoint, elapsed time and feedback with zero model replays', async t => {
  const f = fixture(t), { row, grant } = f.exportAndGrant(f.checkpoint(f.create())); let saved = await f.settled(await f.run(row, grant, 'review')); saved = f.service.transition(saved.id, { ...review(saved), action: 'pause' }); const snapshot = structuredClone(saved); await f.reopen(); assert.deepEqual(f.service.get(saved.id), snapshot); await f.reopen(true); assert.deepEqual(f.service.get(saved.id), snapshot); assert.equal(f.calls, 1); assert.equal(f.store.integrity().integrity, 'ok');
});

test('CP14 unavailable/malformed host produces visibly failed linked request, never a fake solved outcome', async t => {
  const disabled = fixture(t, { enabled: false }), one = disabled.exportAndGrant(disabled.checkpoint(disabled.create())); await assert.rejects(disabled.run(one.row, one.grant), { code: 'UNSUPPORTED' }); assert.equal(disabled.service.get(one.row.id).data.pending.state, 'failed'); assert.equal(disabled.calls, 0);
  const malformed = fixture(t, { executor: async (_, { problem }) => result({ ...question(problem.id), source_refs: [randomUUID()] }) }), two = malformed.exportAndGrant(malformed.checkpoint(malformed.create())); const saved = await malformed.settled(await malformed.run(two.row, two.grant)); assert.equal(saved.data.pending.state, 'failed'); assert.equal(saved.data.pending.error_code, 'VERSION_MISMATCH'); assert.equal(saved.data.coaching.length, 0); assert.equal(saved.code_execution_verified, false);
});

test('CP15 paired route restricts inputs/methods and makes execution or submission unavailable', async t => {
  const f = fixture(t), route = '/coding-practice/state', session = { nonce: 'fixture-paired' }, base = { session, codingPracticeService: f.service, privateBody: async () => ({}) }; assert.equal(await handleCodingPracticeRoute({ route: '/unrelated', method: 'GET' }), null); await assert.rejects(handleCodingPracticeRoute({ route, method: 'GET', ...base, session: null }), { code: 'AUTH_REQUIRED' }); assert.equal((await handleCodingPracticeRoute({ route, method: 'GET', ...base })).status, 200);
  let fields; const created = await handleCodingPracticeRoute({ route: '/coding-practice/sessions', method: 'POST', ...base, privateBody: async allowed => { fields = allowed; return f.input(); }, idempotencyKey: 'coding-route-create' }); assert.equal(created.status, 201); assert.deepEqual(fields, ['problem_ref', 'language', 'mode']); assert.equal(await handleCodingPracticeRoute({ route: `/coding-practice/sessions/${created.data.item.id}/submit`, method: 'POST', ...base }), null); await assert.rejects(handleCodingPracticeRoute({ route, method: 'POST', ...base }), { code: 'INVALID_INPUT' });
});

test('CP16 JSON-encoded context budget is enforced before record/doc/grant/model creation, including escaped text', t => {
  const f = fixture(t, { content: '"'.repeat(13000) }), before = { records: f.store.listWorkspaceRecords({ kind: 'career_item' }).length, notes: f.store.listDocuments().length, grants: f.store.listAgentGrants().length }; assert.throws(() => f.create(), { code: 'BUDGET_EXCEEDED' }); assert.deepEqual({ records: f.store.listWorkspaceRecords({ kind: 'career_item' }).length, notes: f.store.listDocuments().length, grants: f.store.listAgentGrants().length }, before); assert.equal(f.calls, 0);
  const plain = fixture(t, { content: 'A'.repeat(18000) }), row = plain.create(), initial = plain.store.listWorkspaceRecords({ kind: 'career_item' }).length; assert.throws(() => plain.checkpoint(row, 'B'.repeat(10000), 'I compare pairs.'), { code: 'BUDGET_EXCEEDED' }); assert.equal(plain.store.listWorkspaceRecords({ kind: 'career_item' }).length, initial); assert.equal(plain.service.get(row.id).checkpoints.length, 0);
});

test('CP17 code is inert text, including shell-like content; review requires student work and no implicit writes exist', t => {
  const f = fixture(t), created = f.create(), exported = f.exportAndGrant(created); assert.throws(() => f.service.previewRun(exported.row.id, { ...review(exported.row), kind: 'review' }), { code: 'REVISION_CONFLICT' }); const code = 'process.exit(99); require("node:fs").writeFileSync("SHOULD_NOT_EXIST", "bad");'; const saved = f.checkpoint(exported.row, code, ''); assert.equal(saved.checkpoints[0].data.code, code); assert.equal(f.calls, 0); assert.equal(saved.automatic_submission, false); assert.equal(saved.code_execution_verified, false);
});

test('CP18 unavailable host acknowledgment becomes unknown_outcome and retries never re-execute', async t => {
  const f = fixture(t); let starts = 0; const disconnected = { capability: () => ({ state: 'fixture' }), start: async () => { starts++; return { id: randomUUID() }; }, get: () => null, list: () => [] }, service = createCodingPracticeService({ store: f.store, hostTurns: disconnected, leetcodeService: f.leetcode });
  let row = service.create(f.input(), { idempotencyKey: 'coding-unknown-session' }); row = service.exportContext(row.id, review(row)); const grant = f.store.createAgentGrant({ destination: 'codex', task_ids: [], document_ids: [row.data.context_note.id], source_entry_ids: [], max_bytes: 256000, expires_in_minutes: 10 }), preview = service.previewRun(row.id, { ...review(row), kind: 'question' }), input = { ...review(row), kind: 'question', grant_id: grant.id, prompt_sha256: preview.prompt_sha256, confirmed: true }, options = { idempotencyKey: 'coding-unknown-host', authorize: () => true };
  const started = await service.run(row.id, input, options), unknown = service.get(started.id); assert.equal(unknown.data.pending.state, 'unknown_outcome'); assert.equal(unknown.data.pending.error_code, 'HOST_ACK_UNAVAILABLE'); assert.equal(unknown.data.coaching.length, 0); assert.equal((await service.run(row.id, input, options)).data.pending.state, 'unknown_outcome'); assert.equal(starts, 1);
});

test('CP19 revoked historical coaching is omitted from future prompt continuity and cannot be silently reshared', async t => {
  const f = fixture(t, { executor: async (_, { problem }) => result({ ...question(problem.id), message: 'REVOKED_COACHING_CANARY' }) }), initial = f.exportAndGrant(f.checkpoint(f.create())); let row = await f.settled(await f.run(initial.row, initial.grant)); row = f.checkpoint(row, 'return 2', 'I compare pairs.'); const next = f.exportAndGrant(row), grant = f.store.getAgentGrant(initial.grant.id); f.store.revokeAgentGrant(grant.id, grant.revision); const preview = f.service.previewRun(next.row.id, { ...review(next.row), kind: 'hint' }); assert.equal(preview.prompt.includes('REVOKED_COACHING_CANARY'), false); assert.equal(f.service.get(row.id).data.coaching[0].payload, null);
});

test('CP20 explicitly selected saved answer imports exact original code, platform provenance and student explanation without provider reads', async t => {
  const f = fixture(t), source = f.createReport(), input = { submission_ref: { id: source.id, revision: source.revision, sha256: source.sha256 }, explanation: 'I compare pairs.', confirmed: true }; let row = f.create(); const originalHash = row.data.context_hash; row = f.service.importSubmission(row.id, { ...review(row), ...input });
  assert.equal(row.checkpoints.length, 1); assert.equal(row.checkpoints[0].data.code, source.data.code); assert.equal(row.checkpoints[0].data.explanation, input.explanation); assert.equal(row.checkpoints[0].data.origin, 'student_selected_platform_history'); assert.deepEqual(row.checkpoints[0].data.submission_ref, input.submission_ref); assert.equal(row.data.context.checkpoint.platform_result.status_code, 11); assert.equal(row.data.context.checkpoint.platform_result.total_correct, 4); assert.equal(row.data.context.checkpoint.platform_result.correctness, 'platform_reported_not_locally_executed'); assert.equal(row.data.context.checkpoint.platform_result.historical_copy, true); assert.notEqual(row.data.context_hash, originalHash); assert.equal(row.data.context_note, null); assert.equal(row.code_execution_verified, false); assert.equal(f.calls, 0);
  const shared = f.exportAndGrant(row); row = await f.settled(await f.run(shared.row, shared.grant, 'review')); assert.equal(row.data.coaching[0].payload.evidence[0].evidence_quote, input.explanation); assert.equal(row.checkpoints[0].data.platform_result.total_testcases, 20); assert.equal(row.mastery_claim, false);
});

test('CP21 previous answer import rejects wrong problem/account/language and requires exact refs plus explicit explanation and consent', t => {
  const f = fixture(t), row = f.create(); for (const data of [{ slug: 'valid-parentheses' }, { username: 'another-student' }, { language: 'java' }]) { const report = f.createReport(data); assert.throws(() => f.service.importSubmission(row.id, { ...review(row), submission_ref: { id: report.id, revision: report.revision, sha256: report.sha256 }, explanation: 'I compare pairs.', confirmed: true }), { code: 'SCOPE_DENIED' }); }
  const report = f.createReport(), base = { ...review(row), submission_ref: { id: report.id, revision: report.revision, sha256: report.sha256 }, explanation: 'I compare pairs.', confirmed: true };
  assert.throws(() => f.service.importSubmission(row.id, { ...base, confirmed: false }), { code: 'CONSENT_REQUIRED' }); assert.throws(() => f.service.importSubmission(row.id, { ...base, explanation: '' }), { code: 'INVALID_INPUT' }); assert.throws(() => f.service.importSubmission(row.id, { ...base, submission_ref: { ...base.submission_ref, sha256: sha('wrong') } }), { code: 'REVISION_CONFLICT' }); assert.throws(() => f.service.importSubmission(row.id, { ...base, code: 'replacement' }), { code: 'INVALID_INPUT' }); assert.equal(f.service.get(row.id).checkpoints.length, 0); assert.equal(f.calls, 0);
});

test('CP22 saved report edits invalidate source-pinned coaching/context while retaining exact historical checkpoint code', async t => {
  const f = fixture(t), report = f.createReport(), sourceRef = { id: report.id, revision: report.revision, sha256: report.sha256 }; let row = f.create(); row = f.service.importSubmission(row.id, { ...review(row), submission_ref: sourceRef, explanation: 'I compare pairs.', confirmed: true }); const shared = f.exportAndGrant(row); row = await f.settled(await f.run(shared.row, shared.grant, 'review'));
  f.store.updateWorkspaceRecord(report.id, { expected_revision: report.revision, data: { ...report.data, code: 'CHANGED_REPORT_CANARY' } }); const hidden = f.service.get(row.id); assert.equal(hidden.stale, true); assert.equal(hidden.data.context, null); assert.equal(hidden.data.coaching[0].payload, null); assert.equal(hidden.checkpoints[0].data.code, report.data.code); assert.equal(JSON.stringify(hidden).includes('CHANGED_REPORT_CANARY'), false); assert.throws(() => f.service.exportContext(hidden.id, review(hidden)), { code: 'REVISION_CONFLICT' });
});

test('CP23 selected historical answer survives restart/backup without live credential dependence and case-normalized ownership works', async t => {
  const f = fixture(t), report = f.createReport({ username: 'Fixture-Student', language: 'Python3' }); let row = f.create(); row = f.service.importSubmission(row.id, { ...review(row), submission_ref: { id: report.id, revision: report.revision, sha256: report.sha256 }, explanation: 'I compare pairs.', confirmed: true }); row = f.service.transition(row.id, { ...review(row), action: 'pause' }); const snapshot = structuredClone(row); await f.reopen(); assert.deepEqual(f.service.get(row.id), snapshot); await f.reopen(true); assert.deepEqual(f.service.get(row.id), snapshot); assert.equal(f.calls, 0);
});

test('CP24 oversized selected previous code fails context budget before creating a checkpoint, note or grant', t => {
  const f = fixture(t), source = f.createReport({ code: '"'.repeat(13000) }), row = f.create(), before = { rows: f.store.listWorkspaceRecords({ kind: 'career_item' }).length, notes: f.store.listDocuments().length, grants: f.store.listAgentGrants().length }; assert.throws(() => f.service.importSubmission(row.id, { ...review(row), submission_ref: { id: source.id, revision: source.revision, sha256: source.sha256 }, explanation: 'I compare pairs.', confirmed: true }), { code: 'BUDGET_EXCEEDED' }); assert.deepEqual({ rows: f.store.listWorkspaceRecords({ kind: 'career_item' }).length, notes: f.store.listDocuments().length, grants: f.store.listAgentGrants().length }, before); assert.equal(f.service.get(row.id).checkpoints.length, 0);
});

test('CP25 paired previous-answer import route allows only selected source ref, explanation, revision and consent', async t => {
  const f = fixture(t), source = f.createReport(), row = f.create(), input = { ...review(row), submission_ref: { id: source.id, revision: source.revision, sha256: source.sha256 }, explanation: 'I compare pairs.', confirmed: true }; let fields;
  const result = await handleCodingPracticeRoute({ route: `/coding-practice/sessions/${row.id}/import-submission`, method: 'POST', session: { nonce: 'paired-fixture' }, codingPracticeService: f.service, stillAuthorized: () => true, privateBody: async allowed => { fields = allowed; return input; } }); assert.equal(result.status, 200); assert.equal(result.data.item.checkpoints.length, 1); assert.deepEqual(fields, ['expected_revision', 'context_hash', 'submission_ref', 'explanation', 'confirmed']);
});

test('CP26 reviewed prompt explicitly enumerates every allowed assessment, provenance value and required dimension', t => {
  const f = fixture(t), { row } = f.exportAndGrant(f.checkpoint(f.create())), preview = f.service.previewRun(row.id, { ...review(row), kind: 'review' }); assert(preview.prompt.includes('assessment must be exactly observed, missing, or not_assessed')); assert(preview.prompt.includes('dimension approach, complexity, edge_cases, communication')); assert(preview.prompt.includes('evidence_from exactly code or explanation')); assert(preview.prompt.includes('evidence_from exactly none')); assert(preview.prompt.includes('never reviewed')); assert(preview.prompt.includes('historical platform report only'));
});
