import test from 'node:test';
import assert from 'node:assert/strict';
import {handleCalendarImportRoute} from '../apps/local-runtime/src/calendar-import-routes.mjs';
const id='d0b613ae-3aeb-4538-9bdb-0e0a09bb5e84';
function harness(){const calls=[];const service=Object.fromEntries(['context','listPreviews','listSources','preview','accept','forget','plan'].map(name=>[name,(...args)=>{calls.push({name,args});return name.startsWith('list')?[]:{marker:name};}]));return{calls,service,args:{route:'/calendar-import/context',method:'GET',service,session:{nonce:'verified-session'},stillAuthorized(){},privateBody:async()=>({}),idempotencyKey:'route-selected-calendar'}};}
test('CIR01: exact operations dispatch bounded reviewed fields and their idempotency key only',async()=>{const h=harness(),bodyCalls=[];const run=async(route,method,body={})=>handleCalendarImportRoute({...h.args,route,method,privateBody:async(...args)=>(bodyCalls.push(args),body)});
  assert.equal((await run('/calendar-import/context','GET')).data.marker,'context');assert.equal((await run('/calendar-import/previews','GET')).status,200);assert.equal((await run('/calendar-import/sources','GET')).status,200);await run('/calendar-import/previews','POST',{filename:'one.ics'});assert.equal(bodyCalls.at(-1)[2],100000);await run(`/calendar-import/previews/${id}/accept`,'POST',{confirmed:true});assert.deepEqual(bodyCalls.at(-1)[0],['expected_revision','review_hash','selected_indexes','scope','confirmed']);assert.equal(h.calls.at(-1).args[2].idempotencyKey,h.args.idempotencyKey);await run(`/calendar-import/sources/${id}/forget`,'POST',{confirmed:true});assert.equal(h.calls.at(-1).name,'forget');
});
test('CIR02: no pairing and session revocation after awaited private body block any read or mutation',async()=>{const h=harness();await assert.rejects(()=>handleCalendarImportRoute({...h.args,session:null}),{code:'AUTH_REQUIRED'});let revoked=false;await assert.rejects(()=>handleCalendarImportRoute({...h.args,route:'/calendar-import/previews',method:'POST',privateBody:async()=>{revoked=true;return{};},stillAuthorized(){if(revoked)throw Object.assign(new Error(),{code:'AUTH_REQUIRED'});}}),{code:'AUTH_REQUIRED'});assert.equal(h.calls.length,0);});
test('CIR03: unsupported methods and operation aliases never dispatch service calls',async()=>{const h=harness();for(const [route,method]of [['/calendar-import/context','POST'],['/calendar-import/sources','DELETE'],['/calendar-import/plans','GET'],['/calendar-import/fetch','POST'],[`/calendar-import/previews/${id}/send`,'POST'],['/calendar-import/previews/not-a-uuid/accept','POST']])await assert.rejects(()=>handleCalendarImportRoute({...h.args,route,method}));assert.equal(h.calls.length,0);assert.equal(await handleCalendarImportRoute({...h.args,route:'/outside'}),null);});
test('CIR04: planning runs inside bounded source-operation lease and passes cancellation/authorization',async()=>{const h=harness(),controller=new AbortController();let invoked=false;await handleCalendarImportRoute({...h.args,route:'/calendar-import/plans',method:'POST',privateBody:async()=>({availability:[]}),sourceOperation:async operation=>{invoked=true;return await operation(controller.signal);}});assert.equal(invoked,true);const call=h.calls.at(-1);assert.equal(call.name,'plan');assert.equal(call.args[1].signal,controller.signal);assert.equal(typeof call.args[1].authorize,'function');assert.equal(call.args[1].idempotencyKey,h.args.idempotencyKey);});
test('CIR05: revocation after plan operation never returns private plan payload',async()=>{const h=harness();let revoked=false;await assert.rejects(()=>handleCalendarImportRoute({...h.args,route:'/calendar-import/plans',method:'POST',stillAuthorized(){if(revoked)throw Object.assign(new Error(),{code:'AUTH_REQUIRED'});},sourceOperation:async operation=>{const value=await operation();revoked=true;return value;}}),{code:'AUTH_REQUIRED'});});
