import test from 'node:test';
import assert from 'node:assert/strict';
import { handleFocusRoute } from '../apps/local-runtime/src/focus-routes.mjs';
const sessionId = '01368fc2-631c-4220-824f-667d967ff9a7';
function fixture() { const calls = [], service = Object.fromEntries(['context', 'list', 'get', 'start', 'pause', 'resume', 'end', 'discard'].map(name => [name, (...args) => { calls.push({ name, args }); return name === 'list' ? [] : { id: sessionId }; }])); return { calls, service, session: { nonce: 'synthetic' }, privateBody: async () => ({}), stillAuthorized() { calls.push({ name: 'authorize' }); } }; }
test('FSR01: exact paired routes forward selected timer operations and start idempotency key', async () => {
  const f = fixture(); assert.equal(await handleFocusRoute({ ...f, route: '/tasks', method: 'GET' }), null);
  for (const [route, method, name] of [['/focus/context', 'GET', 'context'], ['/focus/sessions', 'GET', 'list'], ['/focus/sessions', 'POST', 'start'], [`/focus/sessions/${sessionId}`, 'GET', 'get'], ...['pause', 'resume', 'end', 'discard'].map(op => [`/focus/sessions/${sessionId}/${op}`, 'POST', op])]) { const result = await handleFocusRoute({ ...f, route, method, idempotencyKey: 'focus-route-key' }); assert.equal(result.status, name === 'start' ? 201 : 200); assert.equal(f.calls.at(-1).name, name); }
  assert.deepEqual(f.calls.find(row => row.name === 'start').args[1], { idempotencyKey: 'focus-route-key' });
});
test('FSR02: missing session denies metadata and mutations before service access', async () => { const f = fixture(); for (const session of [null, {}, { nonce: '' }, { nonce: 42 }]) await assert.rejects(handleFocusRoute({ ...f, route: '/focus/context', method: 'GET', session }), { code: 'AUTH_REQUIRED' }); assert.equal(f.calls.length, 0); });
test('FSR03: authorization revoked during asynchronous body read prevents starting a timer', async () => { const f = fixture(); let valid = true; f.stillAuthorized = () => { if (!valid) { const e = new Error(); e.code = 'AUTH_REQUIRED'; throw e; } }; f.privateBody = async () => { valid = false; return {}; }; await assert.rejects(handleFocusRoute({ ...f, route: '/focus/sessions', method: 'POST' }), { code: 'AUTH_REQUIRED' }); assert.equal(f.calls.length, 0); });
test('FSR04: strict private payload keys/bounds separate timer intention from exact review', async () => { const f = fixture(), bodies = []; f.privateBody = async (...args) => { bodies.push(args); return {}; }; await handleFocusRoute({ ...f, route: '/focus/sessions', method: 'POST' }); await handleFocusRoute({ ...f, route: `/focus/sessions/${sessionId}/pause`, method: 'POST' }); assert.deepEqual(bodies[0], [['title', 'planned_minutes', 'timezone', 'task_id', 'confirmed'], ['title', 'planned_minutes', 'timezone', 'confirmed'], 8000]); assert.deepEqual(bodies[1], [['expected_revision', 'session_hash', 'confirmed'], ['expected_revision', 'session_hash', 'confirmed'], 8000]); });
test('FSR05: unsupported methods/routes cannot complete tasks, capture activity or trigger providers', async () => { const f = fixture(); for (const route of ['/focus/activity', '/focus/notification/send', `/focus/sessions/${sessionId}/complete-task`, '/focus/sessions/not-an-id/end']) await assert.rejects(handleFocusRoute({ ...f, route, method: 'POST' }), { code: 'NOT_FOUND' }); for (const [route, method] of [['/focus/context', 'POST'], ['/focus/sessions', 'PATCH'], [`/focus/sessions/${sessionId}/resume`, 'GET']]) await assert.rejects(handleFocusRoute({ ...f, route, method }), { code: 'METHOD_NOT_ALLOWED' }); assert.equal(f.calls.some(row => row.name !== 'authorize'), false); });
