import test from 'node:test';
import assert from 'node:assert/strict';
import { mountStudentAdminUI } from '../apps/local/public/student-admin.js';
class Node {
  constructor(tag, cls = '', text = '') { this.tagName = tag; this.className = cls; this.text = text; this.children = []; this.listeners = new Map(); this.value = ''; this.disabled = false; this.checked = false; this.classList = { toggle() {} }; }
  append(...values) { this.children.push(...values); } replaceChildren(...values) { this.children = values; this.text = ''; } addEventListener(name, callback) { this.listeners.set(name, [...(this.listeners.get(name) || []), callback]); } setAttribute() {}
  get textContent() { return this.text + this.children.map(child => child.textContent).join(''); } set textContent(value) { this.text = String(value); this.children = []; }
}
const walk = node => [node, ...node.children.flatMap(walk)], fire = (node, type = 'click') => { for (const callback of node.listeners.get(type) || []) callback({ preventDefault() {} }); }, deferred = () => { let resolve; const promise = new Promise(done => { resolve = done; }); return { promise, resolve }; };
const itemId = '01368fc2-631c-4220-824f-667d967ff9a7', previewId = '63f27e68-ac88-40e0-a92d-8f54067a9a98';
const definition = () => ({ title: '<script>ADMIN_TITLE_CANARY</script>', category: 'scholarship', official_url: 'https://university.edu/award', source_text: 'Must be enrolled full time. PRIVATE_PASTED_SOURCE_CANARY', checked_at: '2026-10-04T15:00:00.000Z', timezone: 'America/Toronto', deadline: { precision: 'unknown', original: 'Later this term' }, requirements: [{ key: 'enrollment', excerpt: 'Must be enrolled full time.', status: 'unknown', review_note: 'Enrollment not checked.', profile_fact_ids: [] }], checklist: [] });
const item = (revision = 1) => ({ id: itemId, revision, eligibility: 'unresolved', profile_stale: false, source_changed_since_acceptance: false, accepted_task: null, data: { definition: definition(), source_hash: 'a'.repeat(64), profile_pins: [], item_hash: 'b'.repeat(64), linked_task_id: null, acceptance_preview_id: null } });
const preview = (revision = 1, state = 'prepared') => ({ id: previewId, revision, expired: false, needs_refresh: false, accepted_task: null, data: { definition: definition(), source_hash: 'a'.repeat(64), profile_pins: [], task: { title: 'Review requirements: Scholarship', deadline: { precision: 'unknown' } }, state, review_hash: 'c'.repeat(64), matches: [], eligibility: 'unresolved', blockers: [{ reason: 'requirement_unresolved', excerpt: 'Must be enrolled full time.' }] } });
function harness(t, options = {}) {
  const root = new Node('main'), calls = [], jobs = [], confirmations = [], navigation = []; let items = options.items ?? [], previews = options.previews ?? [];
  const ui = mountStudentAdminUI({ root, element: (tag, cls, text) => new Node(tag, cls, text), request: async (path, extras = {}) => {
    calls.push({ path, ...extras }); const override = options.handle?.(path, extras); if (override !== undefined) return await override;
    if (path === '/student-admin/context') return { profiles: [] };
    if (path === '/student-admin/items' && !extras.method) return { items };
    if (path === '/student-admin/previews') return { items: previews };
    if (path === '/student-admin/items') { const row = item(); row.data.definition = extras.body; items = [row]; return { item: row }; }
    if (path === `/student-admin/items/${itemId}`) { const row = item(2); row.data.definition = extras.body.definition; items = [row]; return { item: row }; }
    if (path.endsWith('/prepare')) { previews = [preview()]; return { item: previews[0] }; }
    if (path.endsWith('/accept')) { previews = [preview(2, 'accepted')]; return { item: previews[0] }; }
    if (path.endsWith('/cancel')) { previews = [preview(2, 'cancelled')]; return { item: previews[0] }; }
    throw new Error(`Unexpected administration UI ${path}`);
  }, busy(target, action) { target.disabled = true; const job = Promise.resolve().then(action).finally(() => { target.disabled = false; }); jobs.push(job); return job; }, confirmAction: async (...args) => { confirmations.push(args); return options.confirm ? await options.confirm(...args) : true; }, navigate: (...args) => navigation.push(args) });
  t.after(() => ui.reset()); const find = predicate => { const node = walk(root).find(predicate); assert(node); return node; }, button = text => find(node => node.tagName === 'button' && node.textContent === text), input = id => find(node => node.id === id);
  return { root, ui, calls, jobs, confirmations, navigation, button, input, set(rows, saved) { items = rows; previews = saved; }, get notice() { return input('student-admin-status').textContent; }, start(caption) { fire(button(caption)); return jobs.at(-1); }, async click(caption) { fire(button(caption)); await jobs.at(-1)?.catch(() => {}); }, async submit() { fire(find(node => node.tagName === 'form'), 'submit'); await jobs.at(-1)?.catch(() => {}); }, fill() { for (const [name, value] of Object.entries({ title: 'Review funding', url: 'https://university.edu/award', source: 'Must be enrolled full time.', 'checked-at': '2026-10-04T15:00:00.000Z', timezone: 'America/Toronto', 'requirement_1-excerpt': 'Must be enrolled full time.' })) input(`student-admin-${name}`).value = value; } };
}
test('SAUI01: opening reads saved local records only, begins unknown/no facts and makes no automatic writes or eligibility decision', async t => { const h = harness(t); await h.ui.refresh(); assert.deepEqual(h.calls.map(call => call.path).sort(), ['/student-admin/context', '/student-admin/items', '/student-admin/previews']); assert.equal(h.input('student-admin-precision').value, 'unknown'); assert.equal(h.input('student-admin-requirement_1-review').value, 'unknown'); assert.equal(h.input('student-admin-requirement_1-fact').value, ''); assert.equal(h.calls.some(call => call.method === 'POST'), false); assert.match(h.root.textContent, /student supplied and unverified/); });
test('SAUI02: reviewed save sends only explicit quotations/status/checklist/unknown deadline and creates no task by itself', async t => { const h = harness(t); await h.ui.refresh(); h.fill(); await h.submit(); const post = h.calls.find(call => call.method === 'POST'); assert.equal(post.path, '/student-admin/items'); assert.equal(post.body.requirements[0].status, 'unknown'); assert.deepEqual(post.body.requirements[0].profile_fact_ids, []); assert.deepEqual(post.body.deadline, { precision: 'unknown', reason: 'Student has not confirmed an exact deadline' }); assert.match(post.idempotencyKey, /^[a-f0-9-]{36}$/); assert.equal(h.calls.some(call => call.path.endsWith('/accept')), false); assert.match(h.notice, /No task or external submission/); });
test('SAUI03: prepare creates a preview only; accepting exact selected preview separately preserves unknown blockers and excludes form submission', async t => { const h = harness(t, { items: [item()] }); await h.ui.refresh(); await h.click('Prepare a local task preview'); assert.equal(h.calls.some(call => call.path.endsWith('/accept')), false); assert.match(h.root.textContent, /Unknown deadline/); assert.match(h.root.textContent, /requirement unresolved/); await h.click('Review and add this local task'); const post = h.calls.find(call => call.path.endsWith('/accept')); assert.deepEqual(post.body, { expected_revision: 1, review_hash: 'c'.repeat(64), confirmed: true }); assert.match(h.confirmations.at(-1)[0], /not official eligibility/); assert.match(h.confirmations.at(-1)[0], /No application, form, calendar or provider data/); });
test('SAUI04: declines, changed input while reviewing, and changed preview revision never inherit old consent', async t => { const declined = harness(t, { confirm: async () => false, previews: [preview()] }); await declined.ui.refresh(); declined.fill(); await declined.submit(); await declined.click('Review and add this local task'); assert.equal(declined.calls.some(call => call.method === 'POST'), false);
  const entered = deferred(), released = deferred(), h = harness(t, { confirm: () => { entered.resolve(); return released.promise; } }); await h.ui.refresh(); h.fill(); const pending = h.submit(); await entered.promise; h.input('student-admin-title').value = 'Changed title'; released.resolve(true); await pending; assert.equal(h.calls.some(call => call.method === 'POST'), false);
  const gate = deferred(), done = deferred(), g = harness(t, { previews: [preview()], confirm: () => { gate.resolve(); return done.promise; } }); await g.ui.refresh(); const accepting = g.start('Review and add this local task'); await gate.promise; g.set([], [preview(2)]); await g.ui.refresh(); done.resolve(true); await accepting; assert.equal(g.calls.some(call => call.method === 'POST'), false);
});
test('SAUI05: record corrections include exact revision/hash and preserve requirement reviews; task link navigation is separate', async t => { const existing = item(); existing.data.linked_task_id = previewId; existing.accepted_task = { id: previewId, title: 'Preserved task', changed: true }; const h = harness(t, { items: [existing] }); await h.ui.refresh(); await h.click('Open local tasks'); assert.deepEqual(h.navigation, [['today']]); await h.click('Correct this record'); h.input('student-admin-title').value = 'Corrected source title'; await h.submit(); const post = h.calls.find(call => call.method === 'POST'); assert.equal(post.path, `/student-admin/items/${itemId}`); assert.equal(post.body.expected_revision, 1); assert.equal(post.body.item_hash, 'b'.repeat(64)); assert.equal(post.body.confirmed, true); assert.equal(post.body.definition.requirements[0].status, 'unknown'); assert.equal(h.calls.some(call => call.path.endsWith('/accept')), false); });
test('SAUI06: expired/stale/matching previews visibly disable creation; source text and hostile titles render as literal text', async t => { const rows = [preview(), preview(), preview()]; rows[0].expired = true; rows[1].needs_refresh = true; rows[2].data.matches = [{ id: itemId }]; const h = harness(t, { items: [item()], previews: rows }); await h.ui.refresh(); assert(walk(h.root).filter(node => node.tagName === 'button' && node.textContent === 'Review and add this local task').every(node => node.disabled)); assert.match(h.root.textContent, /PRIVATE_PASTED_SOURCE_CANARY/); assert.match(h.root.textContent, /<script>ADMIN_TITLE_CANARY<\/script>/); assert.equal(walk(h.root).some(node => node.tagName === 'script'), false); });
test('SAUI07: duplicate review clicks share one confirmation and mutation; failed create retries retain the same exact key', async t => { const entered = deferred(), released = deferred(), h = harness(t, { previews: [preview()], confirm: () => { entered.resolve(); return released.promise; } }); await h.ui.refresh(); const pending = h.start('Review and add this local task'); await entered.promise; fire(h.button('Review and add this local task')); released.resolve(true); await pending; assert.equal(h.confirmations.length, 1); assert.equal(h.calls.filter(call => call.path.endsWith('/accept')).length, 1);
  let failed = false; const g = harness(t, { handle: (path, extras) => { if (path === '/student-admin/items' && extras.method === 'POST' && !failed) { failed = true; return Promise.reject(new Error('Synthetic interrupted save')); } } }); await g.ui.refresh(); g.fill(); await g.submit(); await g.submit(); const posts = g.calls.filter(call => call.path === '/student-admin/items' && call.method === 'POST'); assert.equal(posts.length, 2); assert.equal(posts[0].idempotencyKey, posts[1].idempotencyKey);
});
test('SAUI08: reset during review or delayed metadata prevents writes, private revival and source-editor retention', async t => { const entered = deferred(), released = deferred(), h = harness(t, { items: [item()], previews: [preview()], confirm: () => { entered.resolve(); return released.promise; } }); await h.ui.refresh(); await h.click('Correct this record'); const pending = h.start('Review and add this local task'); await entered.promise; h.ui.reset(); released.resolve(true); await pending; assert.equal(h.calls.some(call => call.method === 'POST'), false); assert.equal(h.input('student-admin-source').value, ''); assert.equal(h.root.textContent.includes('PRIVATE_PASTED_SOURCE_CANARY'), false); assert.equal(h.button('Review and save correction').disabled, true);
  const late = deferred(), g = harness(t, { handle: path => path === '/student-admin/items' ? late.promise : undefined }); const opening = g.ui.refresh(); g.ui.reset(); late.resolve({ items: [item()] }); await opening; assert.equal(g.root.textContent.includes('PRIVATE_PASTED_SOURCE_CANARY'), false); assert.equal(g.button('Review and save record').disabled, true);
});
