import test from 'node:test';
import assert from 'node:assert/strict';
import { mountFocusUI } from '../apps/local/public/focus.js';
class Node {
  constructor(tag, cls = '', text = '') { this.tagName = tag; this.className = cls; this.text = text; this.children = []; this.listeners = new Map(); this.value = ''; this.disabled = false; this.classList = { toggle() {} }; }
  append(...values) { this.children.push(...values); } replaceChildren(...values) { this.children = values; this.text = ''; } addEventListener(name, callback) { this.listeners.set(name, [...(this.listeners.get(name) || []), callback]); } setAttribute() {}
  get textContent() { return this.text + this.children.map(child => child.textContent).join(''); } set textContent(value) { this.text = String(value); this.children = []; }
}
const walk = node => [node, ...node.children.flatMap(walk)], fire = (node, type = 'click') => { for (const callback of node.listeners.get(type) || []) callback({ preventDefault() {} }); }, deferred = () => { let resolve; const promise = new Promise(done => { resolve = done; }); return { promise, resolve }; };
const sessionId = '01368fc2-631c-4220-824f-667d967ff9a7', taskId = '63f27e68-ac88-40e0-a92d-8f54067a9a98';
const session = (revision = 1, state = 'running', extra = {}) => ({ id: sessionId, revision, session_hash: String(revision).repeat(64), pending_interval_ms: 2000, needs_recovery: state === 'interrupted', data: { title: '<script>FOCUS_TITLE_CANARY</script>', state, planned_minutes: 25, timezone: 'America/Toronto', started_at: '2026-10-04T16:00:00.000Z', task_ref: null, observed_active_ms: (revision - 1) * 30000, last_gap: null, last_receipt: null, observations: [], interval_count: revision - 1 }, ...extra });
function harness(t, options = {}) {
  const root = new Node('main'), calls = [], jobs = [], confirmations = []; let sessions = options.sessions ?? [];
  const ui = mountFocusUI({ root, element: (tag, cls, text) => new Node(tag, cls, text), request: async (path, extras = {}) => {
    calls.push({ path, ...extras }); const override = options.handle?.(path, extras); if (override !== undefined) return await override;
    if (path === '/focus/context') return { tasks: [{ id: taskId, title: 'Synthetic task' }], open_session: sessions.find(row => ['running', 'paused', 'interrupted'].includes(row.data.state)) || null };
    if (path === '/focus/sessions' && !extras.method) return { items: sessions };
    if (path === '/focus/sessions') { sessions = [session()]; return { item: sessions[0] }; }
    if (path === `/focus/sessions/${sessionId}`) return { item: sessions[0] };
    const operation = path.split('/').at(-1); if (['pause', 'resume', 'end', 'discard'].includes(operation)) { const current = sessions[0], state = { pause: 'paused', resume: 'running', end: 'completed', discard: 'discarded' }[operation]; sessions = [{ ...current, revision: current.revision + 1, session_hash: 'f'.repeat(64), needs_recovery: false, data: { ...current.data, state } }]; return { item: sessions[0] }; }
    throw new Error(`Unexpected focus UI ${path}`);
  }, busy(target, action) { target.disabled = true; const job = Promise.resolve().then(action).finally(() => { target.disabled = false; }); jobs.push(job); return job; }, confirmAction: async (...args) => { confirmations.push(args); return options.confirm ? await options.confirm(...args) : true; } });
  t.after(() => ui.reset()); const find = predicate => { const node = walk(root).find(predicate); assert(node); return node; }, button = text => find(node => node.tagName === 'button' && node.textContent === text), input = id => find(node => node.id === id);
  return { root, ui, calls, jobs, confirmations, button, input, set(value) { sessions = value; }, get notice() { return input('focus-status').textContent; }, start(caption) { fire(button(caption)); return jobs.at(-1); }, async click(caption) { fire(button(caption)); await jobs.at(-1)?.catch(() => {}); }, async submit() { fire(find(node => node.tagName === 'form'), 'submit'); await jobs.at(-1)?.catch(() => {}); } };
}

test('FSUI01: opening reads local metadata only, selects no associated task, and never starts or certifies attention', async t => { const h = harness(t); await h.ui.refresh(); assert.deepEqual(h.calls.map(call => call.path).sort(), ['/focus/context', '/focus/sessions']); assert.equal(h.input('focus-task').value, ''); assert.equal(h.input('focus-minutes').value, '25'); await h.submit(); assert.equal(h.calls.some(call => call.method === 'POST'), false); assert.match(h.root.textContent, /does not prove attention/); });
test('FSUI02: exact reviewed start creates one timer; associated task remains an uncompleted selection', async t => { const h = harness(t); await h.ui.refresh(); h.input('focus-title').value = 'Study selected notes'; h.input('focus-timezone').value = 'America/Toronto'; h.input('focus-task').value = taskId; await h.submit(); assert.deepEqual(h.calls.find(call => call.method === 'POST').body, { title: 'Study selected notes', planned_minutes: 25, timezone: 'America/Toronto', task_id: taskId, confirmed: true }); assert.equal(h.confirmations.length, 1); assert.match(h.notice, /planned duration is not credited/); assert.equal(walk(h.root).some(node => node.tagName === 'script'), false); assert.match(h.root.textContent, /<script>FOCUS_TITLE_CANARY<\/script>/); });
test('FSUI03: declined start or pause never requests a transition or fresh private timer', async t => { const h = harness(t, { confirm: async () => false }); await h.ui.refresh(); h.input('focus-title').value = 'Declined timer'; await h.submit(); assert.equal(h.calls.some(call => call.method === 'POST'), false); const g = harness(t, { sessions: [session()], confirm: async () => false }); await g.ui.refresh(); await g.click('Pause this focus timer'); assert.equal(g.calls.some(call => call.path === `/focus/sessions/${sessionId}`), false); });
test('FSUI04: heartbeat revision advances during confirmation; same immutable timer is freshly read then paused with latest hash', async t => { const entered = deferred(), released = deferred(), h = harness(t, { sessions: [session()], confirm: () => { entered.resolve(); return released.promise; } }); await h.ui.refresh(); const pending = h.start('Pause this focus timer'); await entered.promise; h.set([session(3)]); await h.ui.refresh(); released.resolve(true); await pending; const post = h.calls.find(call => call.path.endsWith('/pause')); assert.deepEqual(post.body, { expected_revision: 3, session_hash: '3'.repeat(64), confirmed: true }); assert(h.calls.some(call => call.path === `/focus/sessions/${sessionId}`)); });
test('FSUI05: changed state/human receipt/immutable identity cannot inherit prior timer consent', async t => { for (const change of ['state', 'receipt', 'identity']) { const entered = deferred(), released = deferred(), h = harness(t, { sessions: [session()], confirm: () => { entered.resolve(); return released.promise; } }); await h.ui.refresh(); const pending = h.start('End this focus session'); await entered.promise; let changed = session(2, change === 'state' ? 'paused' : 'running'); if (change === 'receipt') changed.data.last_receipt = { operation: 'resume' }; if (change === 'identity') changed.data.planned_minutes = 40; h.set([changed]); await h.ui.refresh(); released.resolve(true); await pending; assert.equal(h.calls.some(call => call.method === 'POST'), false); } });
test('FSUI06: fresh-get state change between confirmation and transition blocks the action', async t => { const h = harness(t, { sessions: [session()], handle: path => path === `/focus/sessions/${sessionId}` ? { item: session(2, 'interrupted') } : undefined }); await h.ui.refresh(); await h.click('Pause this focus timer'); assert.equal(h.calls.some(call => call.method === 'POST'), false); });
test('FSUI07: reset during review/fresh-get or late metadata read prevents timer/control revival', async t => { for (const stage of ['review', 'fresh']) { const entered = deferred(), released = deferred(), h = harness(t, { sessions: [session()], ...(stage === 'review' ? { confirm: () => { entered.resolve(); return released.promise; } } : { handle: path => path === `/focus/sessions/${sessionId}` ? (entered.resolve(), released.promise) : undefined }) }); await h.ui.refresh(); const pending = h.start('End this focus session'); await entered.promise; h.ui.reset(); released.resolve(stage === 'review' ? true : { item: session() }); await pending; assert.equal(h.calls.some(call => call.method === 'POST'), false); assert.equal(h.root.textContent.includes('FOCUS_TITLE_CANARY'), false); assert.equal(h.button('Review and start focus').disabled, true); } });
test('FSUI08: duplicate clicks share one confirmation and exact transition', async t => { const entered = deferred(), released = deferred(), h = harness(t, { sessions: [session()], confirm: () => { entered.resolve(); return released.promise; } }); await h.ui.refresh(); const pending = h.start('Pause this focus timer'); await entered.promise; fire(h.button('Pause this focus timer')); released.resolve(true); await pending; assert.equal(h.confirmations.length, 1); assert.equal(h.calls.filter(call => call.path.endsWith('/pause')).length, 1); });
