import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {mountCalendarImportUI} from '../apps/local/public/calendar-import.js';
import {LocalStore} from '../packages/local-storage/src/index.mjs';
import {createStudentWorkspace} from '../apps/local-runtime/src/student-workspace.mjs';
import {createCalendarImportService} from '../apps/local-runtime/src/calendar-import-service.mjs';
class Node{constructor(tag,cls='',text=''){this.tagName=tag;this.className=cls;this.text=text;this.children=[];this.listeners=new Map();this.checked=false;this.disabled=false;this.value='';this.classList={toggle(){}};}append(...values){this.children.push(...values);}replaceChildren(...values){this.children=values;this.text='';}addEventListener(name,callback){this.listeners.set(name,[...(this.listeners.get(name)||[]),callback]);}setAttribute(){}get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}set textContent(value){this.text=String(value);this.children=[];}}
const walk=node=>[node,...node.children.flatMap(walk)],fire=(node,type='click')=>{for(const callback of node.listeners.get(type)||[])callback({preventDefault(){}});},deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return{promise,resolve};};
const content=(extra='')=>`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Synthetic//EN\r\nBEGIN:VEVENT\r\nUID:selected\r\nDTSTART:20261006T170000Z\r\nDTEND:20261006T180000Z\r\nSUMMARY:<script>PRIVATE_CALENDAR_TITLE</script>\r\n${extra}END:VEVENT\r\nBEGIN:VEVENT\r\nUID:unselected\r\nDTSTART:20261006T180000Z\r\nDTEND:20261006T190000Z\r\nSUMMARY:UNCHECKED_PRIVATE_CALENDAR\r\n${extra}END:VEVENT\r\nEND:VCALENDAR\r\n`;
function file(text=content(),name='selected.ics'){const bytes=new TextEncoder().encode(text);return{name,size:bytes.length,arrayBuffer:async()=>bytes.buffer.slice(0)};}
function harness(t,options={}){
  const root=new Node('main'),base=mkdtempSync(join(tmpdir(),'learnbridge-calendar-ui-')),store=LocalStore.open({root:base,timezone:'UTC'}),workspace=createStudentWorkspace(store),service=createCalendarImportService({store,studentWorkspace:workspace,clock:()=>Date.parse('2026-10-04T16:00:00.000Z')}),jobs=[],calls=[],confirmations=[];store.createTask({title:'Study with busy times',effort_minutes:90,deadline:{precision:'instant',instant:'2026-10-07T20:00:00.000Z'}});
  const ui=mountCalendarImportUI({root,element:(tag,cls,text)=>new Node(tag,cls,text),request:async(path,extra={})=>{calls.push({path,...extra});const override=options.handle?.(path,extra,service);if(override!==undefined)return await override;if(extra.signal?.aborted)throw new Error('Cancelled');
    if(path==='/calendar-import/context')return service.context();if(path==='/calendar-import/previews'&&!extra.method)return{items:service.listPreviews()};if(path==='/calendar-import/sources')return{items:service.listSources()};if(path==='/calendar-import/previews')return{item:service.preview(extra.body,{idempotencyKey:extra.idempotencyKey})};const accepted=/\/previews\/([^/]+)\/accept$/.exec(path);if(accepted)return service.accept(accepted[1],extra.body,{idempotencyKey:extra.idempotencyKey});const forgot=/\/sources\/([^/]+)\/forget$/.exec(path);if(forgot){service.forget(forgot[1],extra.body);return{deleted:true};}if(path==='/calendar-import/plans')return await service.plan(extra.body,{idempotencyKey:extra.idempotencyKey,signal:extra.signal});const plan=/^\/plans\/([^/]+)\/accept$/.exec(path);if(plan)return{plan:workspace.acceptPlan(plan[1],extra.body)};throw new Error(`Unexpected path ${path}`);},busy(target,operation){target.disabled=true;const job=Promise.resolve().then(operation).finally(()=>target.disabled=false);jobs.push(job);return job;},confirmAction:async(...args)=>{confirmations.push(args);return options.confirm?await options.confirm(...args):true;}});
  t.after(()=>{ui.reset();store.close();rmSync(base,{recursive:true,force:true});});const find=predicate=>{const found=walk(root).find(predicate);assert(found);return found;},button=text=>find(n=>n.tagName==='button'&&n.textContent===text),input=id=>find(n=>n.id===id);
  return{root,store,workspace,service,ui,calls,jobs,confirmations,input,button,get notice(){return input('calendar-import-status').textContent;},set(id,value,type='change'){const node=input(id);node.value=value;fire(node,type);},chooseFile(value=file()){input('calendar-import-file').files=[value];fire(input('calendar-import-file'),'change');this.set('calendar-import-timezone','UTC');},async click(caption){fire(button(caption));await jobs.at(-1)?.catch(()=>{});},start(caption){fire(button(caption));return jobs.at(-1);},choose(row=service.listPreviews()[0]){const include=input(`calendar-import-event-${row.id}-0`);include.checked=true;fire(include,'change');this.set(`calendar-import-start-${row.id}`,'2026-10-06T16:00');this.set(`calendar-import-end-${row.id}`,'2026-10-06T20:00');return row;}};
}
async function preview(h){await h.ui.refresh();h.chooseFile();await h.click('Preview selected calendar file');return h.service.listPreviews()[0];}

test('CIUI01: shipped opening performs only local metadata reads with empty file/timezone/source/ranges and no selected records',async t=>{
  const h=harness(t);await h.ui.refresh();assert.deepEqual(h.calls.map(c=>c.path).sort(),['/calendar-import/context','/calendar-import/previews','/calendar-import/sources']);for(const id of ['calendar-import-file','calendar-import-timezone','calendar-import-source','calendar-import-study-start','calendar-import-study-end','calendar-import-plan-timezone'])assert.equal(h.input(id).value,'');await h.click('Preview selected calendar file');assert.equal(h.calls.some(c=>c.method==='POST'),false);assert.match(h.notice,/Choose one .ics file/);assert.equal(h.service.listSources().length,0);
});
test('CIUI02: real selected file hash/bytes→unchecked literal preview→exact confirmed source→explicit plan→separate accept works',async t=>{
  const h=harness(t),row=await preview(h);assert.equal(h.input(`calendar-import-event-${row.id}-0`).checked,false);assert.equal(h.input(`calendar-import-event-${row.id}-1`).checked,false);assert.match(h.root.textContent,/<script>PRIVATE_CALENDAR_TITLE<\/script>/);assert.equal(walk(h.root).some(n=>n.tagName==='script'),false);assert.equal(h.service.listSources().length,0);
  h.choose(row);await h.click('Accept only checked busy times');assert.equal(h.service.listSources().length,1);const source=h.service.listSources()[0];assert.doesNotMatch(JSON.stringify(source),/UNCHECKED_PRIVATE_CALENDAR/);assert.equal(h.input('calendar-import-source').value,'');assert.equal(h.confirmations.length,1);
  h.set('calendar-import-source',source.id);h.set('calendar-import-study-start','2026-10-06T16:00');h.set('calendar-import-study-end','2026-10-06T20:00');h.set('calendar-import-plan-timezone','UTC');await h.click('Prepare calendar-aware study proposal');const body=h.calls.find(c=>c.path==='/calendar-import/plans').body;assert.deepEqual(body.calendar_source,source.source_pin);assert.deepEqual(body.availability,[source.data.scope]);assert.equal(h.workspace.listPlans()[0].data.state,'proposal');await h.click('Review and accept this study plan');assert.equal(h.workspace.listPlans()[0].data.state,'accepted');assert.equal(h.confirmations.length,2);assert.equal(h.store.listAgentGrants().length,0);assert.equal(h.store.listTasks().length,1);
});
test('CIUI03: all unsupported recurrence is visible and zero-event source/plan acceptance is unavailable',async t=>{
  const h=harness(t);await h.ui.refresh();h.chooseFile(file(content('RRULE:FREQ=WEEKLY\r\n')));await h.click('Preview selected calendar file');assert.equal(h.service.listPreviews()[0].data.parsed.events.length,0);assert.equal(h.button('Accept only checked busy times').disabled,true);assert.match(h.root.textContent,/recurrence_not_supported/);assert.match(h.root.textContent,/No supported busy windows/);await h.click('Prepare calendar-aware study proposal');assert.equal(h.service.listSources().length,0);assert.equal(h.workspace.listPlans().length,0);
});
test('CIUI04: denied confirmation and file/zone/range/event changes while review waits prevent source acceptance',async t=>{
  for(const change of ['refused','file','timezone','range','event']){const entered=deferred(),released=deferred(),h=harness(t,{confirm:()=>{entered.resolve();return released.promise;}});const row=await preview(h);h.choose(row);const pending=h.start('Accept only checked busy times');await entered.promise;
    if(change==='file')h.chooseFile(file(content(),'changed.ics'));if(change==='timezone')h.set('calendar-import-timezone','America/Toronto');if(change==='range')h.set(`calendar-import-end-${row.id}`,'2026-10-06T21:00');if(change==='event'){h.input(`calendar-import-event-${row.id}-0`).checked=false;fire(h.input(`calendar-import-event-${row.id}-0`),'change');}released.resolve(change!=='refused');await pending;assert.equal(h.calls.some(c=>c.path.endsWith('/accept')),false);assert.equal(h.service.listSources().length,0);}
});
test('CIUI05: reset during file read/hash/private response prevents late state, and invalid UTF8/mismatched hashes never reaches acceptance',async t=>{
  for(const stage of ['file','hash','response']){const entered=deferred(),released=deferred(),originalCrypto=globalThis.crypto;const h=harness(t,{...(stage==='response'?{handle:(path,extra,service)=>path==='/calendar-import/previews'&&extra.method?(entered.resolve(),released.promise):undefined}:{})});await h.ui.refresh();const chosen=file();if(stage==='file')chosen.arrayBuffer=()=>{entered.resolve();return released.promise;};if(stage==='hash')Object.defineProperty(globalThis,'crypto',{configurable:true,value:{randomUUID:()=>originalCrypto.randomUUID(),subtle:{digest:async(...args)=>{entered.resolve();await released.promise;return await originalCrypto.subtle.digest(...args);}}}});h.chooseFile(chosen);const pending=h.start('Preview selected calendar file');await entered.promise;const posted=h.calls.find(c=>c.path==='/calendar-import/previews'&&c.method);h.ui.reset();released.resolve(stage==='file'?new TextEncoder().encode(content()).buffer:stage==='response'?{item:h.service.preview(posted.body,{idempotencyKey:posted.idempotencyKey})}:null);await pending;Object.defineProperty(globalThis,'crypto',{configurable:true,value:originalCrypto});assert.equal(h.root.textContent.includes('PRIVATE_CALENDAR_TITLE'),false);assert.equal(h.button('Preview selected calendar file').disabled,true);assert.equal(h.notice,'');if(posted)assert.equal(posted.signal.aborted,true);}
  const invalid=harness(t);await invalid.ui.refresh();invalid.chooseFile({name:'invalid.ics',size:1,arrayBuffer:async()=>new Uint8Array([255]).buffer});await invalid.click('Preview selected calendar file');assert.equal(invalid.calls.some(c=>c.method==='POST'),false);assert.match(invalid.notice,/UTF-8/);
  const mismatched=harness(t,{handle:(path,extra,service)=>{if(path==='/calendar-import/previews'&&extra.method){const item=service.preview(extra.body,{idempotencyKey:extra.idempotencyKey});return{item:{...item,data:{...item.data,parsed:{...item.data.parsed,file_sha256:'a'.repeat(64)}}}};}}});await preview(mismatched);assert.match(mismatched.notice,/exact selected bytes/);assert.equal(mismatched.service.listSources().length,0);
});
test('CIUI06: double-click creates one reviewed acceptance, then forget requires review and leaves retained preview explicit',async t=>{
  const entered=deferred(),released=deferred(),h=harness(t,{confirm:()=>{entered.resolve();return released.promise;}}),row=await preview(h);h.choose(row);const pending=h.start('Accept only checked busy times');await entered.promise;fire(h.button('Accept only checked busy times'));released.resolve(true);await pending;assert.equal(h.confirmations.length,1);assert.equal(h.calls.filter(c=>c.path.endsWith('/accept')).length,1);assert.equal(h.service.listSources().length,1);await h.click('Stop using this busy source');assert.equal(h.service.listSources().length,0);assert.match(h.notice,/historical copies remain/);assert.equal(h.service.listPreviews().length,1);
});
test('CIUI07: scope change/reset while plan response waits aborts request and never revives private plan UI',async t=>{
  for(const mode of ['change','reset']){const entered=deferred(),released=deferred(),h=harness(t,{handle:(path,extra)=>path==='/calendar-import/plans'?(entered.resolve(),released.promise):undefined});const row=await preview(h);h.choose(row);await h.click('Accept only checked busy times');const source=h.service.listSources()[0];h.set('calendar-import-source',source.id);h.set('calendar-import-study-start','2026-10-06T16:00');h.set('calendar-import-study-end','2026-10-06T20:00');h.set('calendar-import-plan-timezone','UTC');const pending=h.start('Prepare calendar-aware study proposal');await entered.promise;const call=h.calls.find(c=>c.path==='/calendar-import/plans');if(mode==='reset')h.ui.reset();else h.set('calendar-import-study-end','2026-10-06T21:00');released.resolve({run:{state:'completed'},plan:{data:{plan:{blocks:[{title:'LATE_PLAN_CANARY'}]}}}});await pending;assert.equal(call.signal.aborted,true);assert.equal(h.root.textContent.includes('LATE_PLAN_CANARY'),false);}
});
test('CIUI08: an explicit new file preview after forgetting a source permits fresh reviewed reimport without logout',async t=>{
  const h=harness(t),first=await preview(h);h.choose(first);await h.click('Accept only checked busy times');await h.click('Stop using this busy source');assert.equal(h.service.listSources().length,0);
  await h.click('Preview selected calendar file');const rows=h.service.listPreviews(),next=rows.find(row=>row.data.state==='preview');assert.equal(rows.length,2);assert(next);h.choose(next);const button=walk(h.root).find(node=>node.tagName==='button'&&node.textContent==='Accept only checked busy times'&&!node.disabled);fire(button);await h.jobs.at(-1);assert.equal(h.service.listSources().length,1);assert.notEqual(h.service.listSources()[0].data.preview_id,first.id);
});
