import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, realpathSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { Client } from '@modelcontextprotocol/client';
import { StdioClientTransport } from '@modelcontextprotocol/client/stdio';
import { startRuntime } from '../apps/local-runtime/src/server.mjs';

const API = '/api/local/v1', originalCourseBody = 'PRIVATE_ORIGINAL_GRADED_COURSE_BODY: recursion requires a terminating base case.', unrelatedBody = 'PRIVATE_NOT_GRANTED_AGENT_NOTE';
test('PTA01: paired accepted graded learning handoff→actual MCP metadata policy→scope-wide restricted writing proposals and source-forget denial', async t => {
  const parent = realpathSync(mkdtempSync(join(tmpdir(), 'learnbridge-plan-task-agent-'))), root = join(parent, 'workspace');
  const unsupported = async () => ({ state: 'unsupported', verification: 'synthetic_agent_no_native_source_read' }), runtime = await startRuntime({ dataRoot: root, port: 0, hostAdapter: { enabled: false }, sourceAdapter: { probeSourceCapability: unsupported, probePdfCapability: unsupported, probeOfficeCapability: unsupported,
    describeRoot: async () => { throw new Error('No source discovery'); }, inventorySource: async () => { throw new Error('No source inventory'); }, readSelectedEntry: async () => { throw new Error('No extra source read'); } }, publicJobFetch: async () => { throw new Error('No provider read'); } });
  let client, stderr = ''; t.after(async () => { await client?.close(); await runtime.close(); assert.equal(stderr.includes(originalCourseBody), false); assert.equal(stderr.includes(unrelatedBody), false); rmSync(parent, { recursive: true, force: true }); });
  const paired = await fetch(runtime.origin + API + '/pair', { method: 'POST', headers: { Origin: runtime.origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ code: runtime.createPairingCode() }) }); assert.equal(paired.status, 200); const session = await paired.json(), cookie = paired.headers.get('set-cookie').split(';')[0];
  const call = async (path, body, method = body === undefined ? 'GET' : 'POST') => { const response = await fetch(runtime.origin + API + path, { method, headers: { Cookie: cookie, 'X-LearnBridge-Nonce': session.nonce, ...(body === undefined ? {} : { Origin: runtime.origin, 'Content-Type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); return { status: response.status, data: await response.json() }; };
  const school = { schema_version: 1, institution: { name: 'Synthetic School', origin: 'https://school.fixture.test', timezone: 'America/Toronto' }, account_ref: 'fixture-student', retrieved_at: '2026-10-04T12:00:00.000Z', courses: [{ source_id: 'A', title: 'Synthetic graded course' }], assignments: [], announcements: [], materials: [{ source_id: 'lesson', course_id: 'A', title: 'Base case source', body: originalCourseBody }] };
  const coursePreview = await call('/academic/preview', { export: school, selected_course_ids: ['A'] }); assert.equal(coursePreview.status, 200); const imported = await call('/academic/library-import', { preview_id: coursePreview.data.preview_id, review_hash: coursePreview.data.refresh.review_hash }); assert.equal(imported.status, 201); const snapshot = imported.data.snapshot;
  const scope = { snapshot_ids: [snapshot.id], course_ids: ['A'] }, found = (await call('/courses/search', { ...scope, query: 'terminating' })).data.results[0], citation = { source_id: found.source_id, version_hash: found.version_hash, chunk_id: found.chunk_id };
  const learning = await call('/learning/sessions', { scope, citations: [citation], topic: 'Conceptual recursion review', mode: 'hint', academic_policy: { grading: 'graded', ai_rule: 'scaffolding_only' } }); assert.equal(learning.status, 201); const tutor = learning.data.item;
  const start = '2026-10-05T13:00:00.000Z', end = '2026-10-05T14:00:00.000Z', prepared = await call(`/learning/sessions/${tutor.id}/catch-up`, { expected_revision: tutor.revision, session_hash: tutor.data.recipe.session_hash, topics: [{ id: 'review', title: 'Review the base-case concept', effort_minutes: 30, source_citations: [citation] }], selected_topic_ids: ['review'], exam: { title: 'Synthetic study goal', deadline: { precision: 'unknown' } }, planning_input: { now: start, horizonEnd: end, timezone: 'America/Toronto', availability: [{ start, end }] } }); assert.equal(prepared.status, 201);
  const acceptedPlan = await call(`/learning/plans/${prepared.data.item.id}/accept`, { expected_revision: prepared.data.item.revision, plan_hash: prepared.data.item.data.plan.plan_hash, catch_up_hash: prepared.data.item.data.catch_up.catch_up_hash }); assert.equal(acceptedPlan.status, 200); const plan = acceptedPlan.data.item;
  const taskPreview = await fetch(runtime.origin + API + '/plan-tasks/previews', { method: 'POST', headers: { Origin: runtime.origin, 'Content-Type': 'application/json', Cookie: cookie, 'X-LearnBridge-Nonce': session.nonce, 'Idempotency-Key': 'synthetic-agent-handoff-preview' }, body: JSON.stringify({ plan_ref: { id: plan.id, revision: plan.revision, plan_hash: plan.data.plan.plan_hash, catch_up_hash: plan.data.catch_up.catch_up_hash }, topic_ids: ['review'] }) }); assert.equal(taskPreview.status, 201); const preview = (await taskPreview.json()).preview;
  const acceptedTask = await call(`/plan-tasks/previews/${preview.id}/accept`, { expected_revision: preview.revision, preview_hash: preview.data.preview_hash, topic_id: 'review', task_hash: preview.rows[0].task_hash, confirmed: true }); assert.equal(acceptedTask.status, 200); const task = acceptedTask.data.task;
  const noteText = 'Selected unrestricted writing note. Explain structure only.', note = (await call('/documents', { title: 'Selected unrelated writing note', content: noteText, academic_policy: 'unrestricted' })).data.document; await call('/documents', { title: 'Unselected note', content: unrelatedBody, academic_policy: 'unrestricted' });
  const granted = await call('/agent-grants', { destination: 'codex', task_ids: [task.id], document_ids: [note.id], source_entry_ids: [], expected_records: { tasks: [{ id: task.id, revision: task.revision }], documents: [{ id: note.id, revision: note.revision }], source_entries: [] }, max_bytes: 48000, expires_in_minutes: 60 }); assert.equal(granted.status, 201, JSON.stringify(granted.data)); const grant = granted.data.grant;
  const transport = new StdioClientTransport({ command: process.execPath, args: [fileURLToPath(new URL('../apps/local-runtime/src/mcp.mjs', import.meta.url)), '--data-root', root, '--destination', 'codex', '--grant-id', grant.id], env: { PATH: '/usr/bin:/bin' }, stderr: 'pipe' }); transport.stderr.on('data', chunk => { stderr += chunk; }); client = new Client({ name: 'synthetic-handoff-policy-verifier', version: '1' }); await client.connect(transport);
  const tool = async (name, args) => { const response = await client.callTool({ name, arguments: args }); return { failed: response.isError === true, value: JSON.parse(response.content[0].text) }; };
  const context = await tool('learnbridge_context', { grant_id: grant.id }); assert.equal(context.failed, false, JSON.stringify(context)); assert.equal(context.value.tasks.length, 1); assert.equal(context.value.documents.length, 1); assert.equal(context.value.source_entries.length, 0); assert.equal(context.value.documents[0].text, noteText);
  const annotation = context.value.tasks[0].source; assert.equal(annotation.metadata_only, true); assert.equal(annotation.academic_policy, 'graded_restricted'); assert.equal(annotation.provenance_receipts.length, 1); assert.equal(annotation.provenance_receipts[0].source.plan_id, plan.id); assert.deepEqual(annotation.provenance_receipts[0].source.academic_policy, { grading: 'graded', ai_rule: 'scaffolding_only' }); assert.equal(annotation.provenance_receipts[0].local_task_differs, false);
  assert.deepEqual(annotation.provenance_pins.map(pin => pin.kind), ['learning_plan_task_receipt', 'learning_catchup_plan', 'tutoring_session', 'learning_academic_snapshot']);
  const serialized = JSON.stringify(context.value); assert.equal(serialized.includes(originalCourseBody), false); assert.equal(serialized.includes(unrelatedBody), false); assert.equal(serialized.includes('source_citations'), false); assert.equal(serialized.includes('reviewed_task'), false); assert.equal(serialized.includes('fixture-student'), false); assert.equal(context.value.serialized_bytes, Buffer.byteLength(serialized));
  const base = { grant_id: grant.id, source_document_id: note.id, source_revision: note.revision, source_sha256: createHash('sha256').update(noteText).digest('hex'), title: 'Conceptual outline proposal', draft: 'Discuss the concept; ask a teach-back question. No graded answer.', academic_policy: 'not_applicable' };
  for (const purpose of ['revision', 'general']) { const denied = await tool('learnbridge_propose_document', { ...base, purpose, idempotency_key: `synthetic-denied-${purpose}` }); assert.equal(denied.failed, true); assert.equal(denied.value.error.code, 'SCOPE_DENIED'); }
  assert.equal((await call('/writing/items')).data.items.length, 0); const outline = await tool('learnbridge_propose_document', { ...base, purpose: 'outline', idempotency_key: 'synthetic-allowed-outline' }); assert.equal(outline.failed, false, JSON.stringify(outline)); assert.equal(outline.value.state, 'awaiting_review');
  const writing = (await call(`/writing/items/${outline.value.id}`)).data.item; assert.equal(writing.data.academic_policy, 'graded_restricted'); assert.equal(writing.data.payload.academic_policy, 'graded_restricted'); assert.equal(writing.data.state, 'awaiting_review'); assert.equal((await call('/documents')).data.items.length, 2); assert.equal((await call('/tasks')).data.items.length, 1);
  const currentSnapshot = (await call('/courses')).data.items.find(item => item.id === snapshot.id), forgotten = await call(`/courses/${snapshot.id}`, { expected_revision: currentSnapshot.revision, expected_stream_revision: currentSnapshot.stream_revision }, 'DELETE'); assert.equal(forgotten.status, 200, JSON.stringify(forgotten.data));
  for (const [name, input] of [['learnbridge_context', { grant_id: grant.id }], ['learnbridge_context', { grant_id: grant.id, task_ids: [], document_ids: [note.id], source_entry_ids: [] }], ['learnbridge_propose_document', { ...base, purpose: 'outline', idempotency_key: 'synthetic-stale-outline' }], ['learnbridge_propose_task', { grant_id: grant.id, title: 'Must not propose after source forget', idempotency_key: 'synthetic-stale-task' }]]) {
    const denied = await tool(name, input); assert.equal(denied.failed, true, name); assert.ok(['VERSION_MISMATCH', 'REVISION_CONFLICT', 'SCOPE_DENIED'].includes(denied.value.error.code)); assert.equal(JSON.stringify(denied).includes(originalCourseBody), false);
  }
  assert.equal((await call('/writing/items')).data.items.length, 1); assert.equal((await call('/task-proposals')).data.items.length, 0); assert.equal((await call('/tasks')).data.items.length, 1); assert.equal((await call('/documents')).data.items.length, 2);
});
