'use client';
import {useEffect,useState} from 'react';
export default function Login(){
 const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('auth_error'))setMessage('Sign-in could not be completed. Please try again.');},[]);
 async function google(){setBusy(true);setMessage('');try{const r=await fetch('/api/auth/google',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.error);window.location.assign(d.url);}catch(e){setMessage(e instanceof Error?e.message:'Could not start Google sign-in.');setBusy(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch(`/api/auth/${signup?'signup':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error);if(signup)setMessage(d.message);else window.location.assign('/');}catch(e){setMessage(e instanceof Error?e.message:'Could not sign in.');}finally{setBusy(false);}}
 return <main className="max-w-md mx-auto px-6 py-16"><p className="text-teal-300">Your learning, connected</p><h1 className="text-4xl font-semibold mt-4 mb-3">{signup?'Join LearnBridge':'Welcome back'}</h1><p className="text-slate-400 mb-8">Your own courses, connections, tasks, and drafts—available wherever you study.</p><button type="button" onClick={google} disabled={busy} className="w-full bg-white text-slate-950 p-3 rounded-lg font-semibold disabled:opacity-40">Continue with Google</button><p className="text-sm text-slate-400 mt-3 mb-6">Sign in or create an account with Google. Access to your apps is connected separately.</p><p className="text-center text-slate-500 mb-6">or use email</p><form onSubmit={submit} className="space-y-5"><label className="block">Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} className="block w-full mt-2 rounded-lg bg-slate-900 border border-slate-700 p-3"/></label><label className="block">Password<input type="password" autoComplete={signup?'new-password':'current-password'} minLength={8} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} className="block w-full mt-2 rounded-lg bg-slate-900 border border-slate-700 p-3"/></label><button disabled={busy} className="w-full bg-teal-300 text-slate-950 p-3 rounded-lg font-semibold disabled:opacity-40">{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form>{message&&<p role="status" className="mt-5 text-amber-200">{message}</p>}<button className="mt-6 text-teal-300" onClick={()=>{setSignup(!signup);setMessage('');}}>{signup?'Already have an account? Sign in':'New here? Create an account'}</button><p className="mt-8 text-xs leading-5 text-slate-500">By using LearnBridge, you agree to our <a className="underline hover:text-teal-300" href="/terms">Terms</a> and acknowledge our <a className="underline hover:text-teal-300" href="/privacy">Privacy Policy</a>.</p></main>;
}
