'use client';
import {loadState,saveState} from '@/lib/cloud-state';
import { useEffect,useState } from 'react';
type Task={id:string;title:string;course:string;due:string;done:boolean};
export default function Home(){
 const [tasks,setTasks]=useState<Task[]>([]),[ready,setReady]=useState(false),[title,setTitle]=useState(''),[course,setCourse]=useState(''),[due,setDue]=useState(''),[error,setError]=useState('');
 const [revision,setRevision]=useState(0),[saving,setSaving]=useState(false);
 useEffect(()=>{let alive=true;loadState('tasks').then(d=>{if(!alive)return;if(Array.isArray(d.value))setTasks(d.value);setRevision(d.revision);setReady(true);}).catch(e=>setError(e.message));return()=>{alive=false;};},[]);
 async function save(next:Task[]){if(saving||!ready)return false;setSaving(true);try{const r=await saveState('tasks',next,revision);setRevision(r);setTasks(next);setError('');return true;}catch(e){setError(e instanceof Error?e.message:'Could not save.');return false;}finally{setSaving(false);}}
 return <main className="max-w-6xl mx-auto px-6 py-12"><p className="text-teal-300 uppercase tracking-widest text-xs">Your student workspace</p><h1 className="text-4xl md:text-6xl font-semibold mt-4 mb-5">A clearer next step.</h1><p className="text-slate-400 max-w-2xl text-lg">Bring your courses together. Understand what matters, plan your week, and learn with support.</p><div className="grid md:grid-cols-3 gap-4 my-10">{[['/connections','Connect your world','Bring course information and updates into one place.'],['/tutor','Work through a concept','Ask for an explanation, a hint, or a study plan.'],['/workspace','Make a start','Draft your work and review suggested improvements.']].map(([href,name,desc])=><a key={href} href={href} className="rounded-2xl border border-slate-700 p-6 bg-slate-900 hover:border-teal-400"><h2 className="text-xl font-semibold mb-3">{name} ↗</h2><p className="text-slate-400">{desc}</p></a>)}</div><section className="rounded-2xl border border-slate-800 p-6"><div className="flex justify-between flex-wrap gap-2"><h2 className="text-2xl">Your next steps</h2><span className="text-sm text-slate-400">Saved to your account · manually added</span></div><form className="grid md:grid-cols-[2fr_1fr_1fr_auto] gap-3 my-5" onSubmit={async e=>{e.preventDefault();if(!title.trim())return;const saved=await save([...tasks,{id:crypto.randomUUID(),title:title.trim(),course:course.trim(),due,done:false}]);if(saved)setTitle('');}}><input aria-label="Task" placeholder="What do you need to do?" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={300} className="bg-slate-900 border border-slate-700 p-3 rounded-lg"/><input aria-label="Course" placeholder="Course (optional)" value={course} onChange={e=>setCourse(e.target.value)} className="bg-slate-900 border border-slate-700 p-3 rounded-lg"/><input aria-label="Due date" type="date" value={due} onChange={e=>setDue(e.target.value)} className="bg-slate-900 border border-slate-700 p-3 rounded-lg"/><button disabled={!ready||saving} className="bg-teal-300 text-slate-950 rounded-lg px-5 py-3 font-semibold">Add task</button></form>{error&&<p role="alert" className="text-rose-300">{error}</p>}{!tasks.length&&<p className="text-slate-400 py-6">No tasks yet. Add one above. Connected deadlines will appear here once course sync is implemented.</p>}{tasks.map(t=><label key={t.id} className="flex items-center gap-4 py-4 border-t border-slate-800"><input type="checkbox" disabled={!ready||saving} checked={t.done} onChange={()=>save(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><span className={t.done?'line-through text-slate-500':''}>{t.title}</span><span className="ml-auto text-sm text-slate-400">{t.course} {t.due&&`· ${t.due}`}</span></label>)}</section></main>;
}
