export const metadata={title:'Privacy Policy · LearnBridge'};

export default function PrivacyPage(){return <main className="mx-auto max-w-3xl px-6 py-12 leading-7 text-slate-300">
 <p className="text-sm text-teal-300">LearnBridge</p><h1 className="my-3 text-4xl font-semibold text-white">Privacy Policy</h1><p className="mb-8 text-sm text-slate-400">Last updated October 3, 2026</p>
 <p className="mb-5">LearnBridge is a student learning workspace operated by Sachin Gupta. This policy explains what information the app handles and how it is used.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Information you provide</h2><p>When you sign in, LearnBridge receives basic account information such as your email address and, where provided, your name and profile image. Tasks and writing drafts you save are stored in your LearnBridge account. LearnBridge uses secure sign-in cookies to keep you signed in.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Connected accounts and AI requests</h2><p>Connecting another service is optional. The provider handles its sign-in and permission screen. LearnBridge uses Composio to manage those connections. When you choose specific connected accounts for a tutor question, LearnBridge can search only the read tools enabled for those accounts. It sends the question and retrieved information to OpenAI to generate a response. Writing suggestions also send the selected text and your instructions to OpenAI when you request them. Do not include information you do not want processed by these services.</p>
 <p className="mt-4">LearnBridge requests that OpenAI not store Responses API outputs. That setting does not control all processing or retention by OpenAI or other providers; their own privacy and service terms also apply. Tutor conversation history is kept in your browser for follow-up requests. LearnBridge does not send connected-account content to the tutor unless you select an account for that request.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Service providers</h2><p>LearnBridge relies on Vercel for website hosting, Supabase for account sign-in and saved workspace data, Composio for connected-account authorization and tool access, and OpenAI for AI responses. Google sign-in uses Google to authenticate your identity. These providers process information as needed to provide their services under their own terms and privacy practices.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Private local edition</h2><p>The optional local edition saves its workspace on your computer. Setup does not scan your laptop or connect accounts. You choose folders and imported records, and separately choose any expiring sharing grant for an official coding-agent host. The host may process shared context under its own account settings. Deleting a local record can leave text in revision history, exported notes and backups; revocation stops future sharing but cannot recall information already sent. Local use does not enroll reporting or remote access.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Optional product reporting</h2><p>Reporting is off by default. If made available, the setup page offers a separate choice for that page session to send a page-view or browser-copy observation: a random event ID, event type, fixed setup route, schema and prompt version. It does not send names, emails, account or device IDs, prompt text, referrers, coursework or local files. A signed-in student can separately choose account enrollment and successful hosted-save counts, and additionally allow authorized LearnBridge admins to view their confirmed account email and provider/user-supplied display name. Anonymous click history is not joined to account identity, and neither choice is marketing consent.</p>
 <p className="mt-4">Raw reporting observations are retained for at most 30 days; anonymous aggregate counts may remain for 12 months. Account reporting opt-out removes raw account activity and directory access; private consent settings remain until changed or account deletion. Turning off a page-session choice clears unsent observations and stops future sends. Ordinary hosting requests and security logs are separate from this optional reporting. The setup page shows availability and the exact fields before a choice; copying the prompt or signing in does not opt you in.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Storage, security, and retention</h2><p>Saved tasks and drafts are associated with your account and protected by account-level access controls. LearnBridge uses HTTPS and server-managed authentication cookies. No internet service can promise perfect security. Saved workspace information remains until it is removed or you request account/data deletion. The app does not yet have a self-service account deletion control; email a request from your account address to <a className="underline text-teal-300" href="mailto:sachinvgupta9@gmail.com">sachinvgupta9@gmail.com</a>. We may retain limited records where needed for security, legal, or operational reasons.</p>
 <h2 className="mb-2 mt-8 text-2xl font-semibold text-white">Your choices and contact</h2><p>You can choose whether to connect services and which connected accounts to use for a tutor request. You can revoke a provider’s authorization in that provider’s account settings. For privacy questions, access or deletion requests, contact <a className="underline text-teal-300" href="mailto:sachinvgupta9@gmail.com">sachinvgupta9@gmail.com</a>.</p>
 <p className="mt-8 text-sm text-slate-400">LearnBridge is under active development. This policy will be updated when data practices materially change.</p>
 </main>;}
