'use client';
import {useEffect,useRef,useState} from 'react';
import {phoneRelay,phoneStudyRequest,verifyPhoneResult} from './remote-phone-client.mjs';
type Binding={id:string;state:string;expires_at:string;last_seen_at:string|null};
type Job={id:string;binding_id:string;state:string};
type Result={id:string;job_id:string;state:string;result_bytes:number;expires_at:string;content_status:string};
const button='rounded-lg border border-slate-600 px-4 py-2 disabled:opacity-40';
export default function RemoteCompanion({enabled,resultsEnabled}:{enabled:boolean;resultsEnabled:boolean}){
 const [bindings,setBindings]=useState<Binding[]>([]),[jobs,setJobs]=useState<Job[]>([]),[results,setResults]=useState<Result[]>([]),[binding,setBinding]=useState(''),[pairing,setPairing]=useState(''),[prompt,setPrompt]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[answer,setAnswer]=useState<{text:string;sha256:string;contentStatus:string;expiresAt:string}|null>(null);
 const pendingQuestion=useRef<ReturnType<typeof phoneStudyRequest>|null>(null);
 const epoch=useRef(0),controller=useRef<AbortController|null>(null),selected=useRef(''); selected.current=binding;
 function invalidate(){pendingQuestion.current=null;epoch.current++;controller.current?.abort();controller.current=null;setBusy(false);setAnswer(null);setPairing('');setPrompt('');setConsent(false);}
 useEffect(()=>{const clear=()=>{if(document.hidden)invalidate();};document.addEventListener('visibilitychange',clear);return()=>{epoch.current++;controller.current?.abort();document.removeEventListener('visibilitychange',clear);};},[]);
 useEffect(()=>{if(!answer)return;const timer=setTimeout(()=>setAnswer(null),Math.max(0,Date.parse(answer.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[answer]);
 async function refresh(signal?:AbortSignal,expected=epoch.current,chosen=selected.current){
  const status=await phoneRelay({bindingId:chosen||undefined,signal});if(expected!==epoch.current)return;setAnswer(null);
  const valid=(status.bindings||[]).filter((row:Binding)=>row.state==='active'&&Date.parse(row.expires_at)>Date.now());setBindings(valid);setJobs(status.jobs||[]);
  if(chosen&&!valid.some((row:Binding)=>row.id===chosen)){setBinding('');selected.current='';invalidate();setResults([]);setNotice('That pairing expired or changed. Pair again, or use account recovery.');return;}
  if(chosen&&resultsEnabled){const response=await phoneRelay({bindingId:chosen,results:true,signal});if(expected===epoch.current)setResults(response.items||[]);}else setResults([]);
 }
 async function action(work:(signal:AbortSignal,expected:number)=>Promise<void>){if(busy)return;const expected=epoch.current,active=new AbortController();controller.current?.abort();controller.current=active;setBusy(true);setNotice('');try{await work(active.signal,expected);}catch(error){if(expected===epoch.current){setAnswer(null);setNotice(error instanceof Error?error.message:'The action could not be verified.');}}finally{if(controller.current===active){controller.current=null;setBusy(false);}}}
 async function select(value:string){invalidate();setBinding(value);selected.current=value;setResults([]);void action(async(signal,expected)=>refresh(signal,expected,value));}
 if(!enabled)return <section className="rounded-xl border border-slate-700 p-6"><h2 className="text-xl font-semibold">Phone access is in preparation</h2><p className="mt-3 leading-7 text-slate-300">Phone pairing and reviewed replies are being verified. Access stays disabled until account, device and retention checks pass. You can use local LearnBridge independently.</p><a href="/setup" className="mt-4 inline-block text-teal-300 underline">Set up your local workspace</a></section>;
 return <div className="space-y-6"><p role="status" aria-live="polite" className="text-amber-200">{notice}</p>
  <section className="rounded-xl border border-slate-700 p-5"><h2 className="text-xl font-semibold">1. Pair your computer</h2><p className="my-3 text-slate-300">Generate a five-minute code, then paste its JSON into Phone access in the local dashboard. Choose a current source sharing grant there. No setup step pairs a computer automatically.</p>
   <div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={()=>void action(async(signal,expected)=>{if(!window.confirm('Pair this signed-in LearnBridge account with your own computer? The relay will process questions you explicitly submit. Pairing alone does not share answer text.'))return;const value=await phoneRelay({operation:'pair',body:{},signal});if(expected===epoch.current)setPairing(JSON.stringify({pending_id:value.pending_id,challenge:value.challenge}));})}>Create pairing code</button><button className={button} disabled={busy} onClick={()=>void action(async(signal,expected)=>refresh(signal,expected))}>Refresh computers and requests</button></div>
   {pairing&&<label className="mt-4 block">Copy this JSON to your computer<textarea readOnly value={pairing} className="mt-2 block min-h-24 w-full rounded-lg bg-slate-900 p-3"/><p className="mt-2 text-sm text-slate-400">Keep it private. It expires in five minutes.</p></label>}
   <label className="mt-4 block">Paired computer<select className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-900 p-3" value={binding} disabled={busy} onChange={event=>void select(event.target.value)}><option value="">Choose a computer</option>{bindings.map(row=><option key={row.id} value={row.id}>{row.id.slice(0,8)} · expires {new Date(row.expires_at).toLocaleTimeString()}</option>)}</select></label>
  </section>
  <section className="rounded-xl border border-slate-700 p-5"><h2 className="text-xl font-semibold">2. Ask a study question</h2><p className="my-3 text-slate-300">Keep the local Phone access page open with foreground polling. Your computer prepares cited study context. If you separately allow its verified Codex adapter, it generates a writing draft for local review.</p>
   <label className="block">Your exact question<textarea value={prompt} disabled={busy} maxLength={4000} onChange={event=>{pendingQuestion.current=null;setPrompt(event.target.value);setConsent(false);}} className="mt-2 block min-h-28 w-full rounded-lg border border-slate-700 bg-slate-900 p-3"/></label>
   <label className="my-4 flex items-start gap-3"><input type="checkbox" disabled={busy} checked={consent} onChange={event=>setConsent(event.target.checked)} className="mt-1"/><span>I approve sending this exact question through the trusted LearnBridge relay. It can read the plaintext; the retention policy is 24 hours. I choose what to include.</span></label>
   <button className={button} disabled={busy||!binding||!consent||!prompt.trim()} onClick={()=>void action(async(signal,expected)=>{const chosen=binding,exact=prompt,request=pendingQuestion.current?.binding_id===chosen&&pendingQuestion.current.prompt===exact?pendingQuestion.current:phoneStudyRequest(chosen,exact);pendingQuestion.current=request;const status=await phoneRelay({bindingId:chosen,signal});if(expected!==epoch.current||!status.bindings.some((row:Binding)=>row.id===chosen&&row.state==='active'&&Date.parse(row.expires_at)>Date.now()))throw Error('Pairing is no longer current. Refresh first.');if(!window.confirm(`Send this exact study question to your computer through the plaintext relay?\n\n${exact}`))return;const value=await phoneRelay({operation:'submit',bindingId:chosen,body:request,signal});if(expected!==epoch.current)return;pendingQuestion.current=null;setPrompt('');setConsent(false);setNotice(`Question queued (${value.id.slice(0,8)}). Review the proposed answer on your computer before sharing.`);await refresh(signal,expected,chosen);})}>Review and send question</button>
   <div className="mt-4 space-y-3">{jobs.filter(row=>row.binding_id===binding).map(row=><div key={row.id} className="rounded-lg border border-slate-800 p-3"><p>{row.id.slice(0,8)} · {row.state.replaceAll('_',' ')}</p><div className="mt-2 flex gap-3">{['cancel','delete'].map(operation=><button key={operation} className={button} disabled={busy} onClick={()=>void action(async(signal,expected)=>{if(!window.confirm(operation==='delete'?'Erase this question from active relay storage and request cancellation? Delivered copies cannot be recalled.':'Request cancellation? Work already delivered to a host cannot be recalled.'))return;const value=await phoneRelay({operation,bindingId:binding,body:{job_id:row.id},signal});if(expected!==epoch.current)return;setAnswer(null);await refresh(signal,expected);setNotice(operation==='delete'?'The relay acknowledged prompt erasure. Check cancellation status separately.':value.cancellation_acknowledged?'Cancellation acknowledged.':'Cancellation requested; waiting for the computer acknowledgment.');})}>{operation==='delete'?'Erase relay question':'Request cancellation'}</button>)}</div></div>)}</div>
  </section>
  <section className="rounded-xl border border-slate-700 p-5"><h2 className="text-xl font-semibold">3. Read a reviewed response</h2><p className="my-3 text-slate-300">Approve the writing item and its exact response on your computer, then choose Send reviewed response. Every read below asks your computer for a fresh check and a one-use delivery ticket. Keep it online and polling.</p>
   {!resultsEnabled&&<p className="text-amber-200">Reviewed text delivery is awaiting additional release checks. Pairing remains a status-only flow.</p>}
   {results.map(row=><div key={row.id} className="mb-3 rounded-lg border border-slate-800 p-3"><p>{row.job_id.slice(0,8)} · {row.state} · {row.result_bytes} bytes</p><div className="mt-2 flex flex-wrap gap-3"><button className={button} disabled={busy||row.state!=='available'||Date.parse(row.expires_at)<=Date.now()} onClick={()=>void action(async(signal,expected)=>{setAnswer(null);const chosen=binding;const delivery=await phoneRelay({operation:'begin_delivery',bindingId:chosen,results:true,body:{result_id:row.id},signal});const deadline=Math.min(Date.now()+60000,Date.parse(delivery.expires_at));while(Date.now()<deadline){if(expected!==epoch.current)return;try{const value=await phoneRelay({operation:'read',bindingId:chosen,results:true,body:{delivery_id:delivery.id},signal});const verified=await verifyPhoneResult(value,{bindingId:chosen,resultId:row.id,deliveryId:delivery.id});if(expected===epoch.current&&selected.current===chosen){setAnswer(verified);setNotice('Exact reviewed response verified. Model-generated claims still require your judgment.');}return;}catch(error){if((error as {code?:string}).code!=='REMOTE_DELIVERY_WAITING')throw error;}await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{signal.removeEventListener('abort',abort);resolve();},1000);const abort=()=>{clearTimeout(timer);reject(Error('Read cancelled.'));};signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort();});}throw Error('Your computer did not approve a current delivery. Keep its phone page polling, then try again.');})}>Read with fresh computer check</button>
    <button className={button} disabled={busy} onClick={()=>void action(async(signal,expected)=>{if(!window.confirm('Revoke this response and erase its active relay text? Already delivered copies cannot be recalled.'))return;await phoneRelay({operation:'delete',bindingId:binding,results:true,body:{result_id:row.id},signal});if(expected===epoch.current){setAnswer(null);await refresh(signal,expected);setNotice('The relay acknowledged response erasure.');}})}>Erase relay response</button></div></div>)}
   {answer&&<article className="mt-4 rounded-lg border border-teal-800 p-4"><p className="mb-3 text-sm text-slate-400">{answer.contentStatus==='student_reviewed_model_output_facts_unverified'?'Locally reviewed model output; facts unverified':'Locally reviewed content'}</p><pre className="whitespace-pre-wrap break-words font-sans leading-7">{answer.text}</pre><p className="mt-3 break-all text-xs text-slate-400">Exact text SHA-256: {answer.sha256}</p><button className={`${button} mt-3`} onClick={()=>setAnswer(null)}>Clear this phone view</button></article>}
  </section>
  <section className="rounded-xl border border-slate-700 p-5"><h2 className="text-xl font-semibold">Stop or recover</h2><p className="my-3 text-slate-300">A restart, sign-out or restored workspace requires pairing again. If the computer lost its memory-only credential, revoke old pairings here first. Already delivered copies and local history or backups may retain text.</p><div className="flex flex-wrap gap-3"><button className={button} disabled={busy||!binding} onClick={()=>void action(async(signal,expected)=>{if(!window.confirm('Revoke this computer pairing and block future relay reads?'))return;await phoneRelay({operation:'revoke',bindingId:binding,body:{},signal});if(expected===epoch.current){invalidate();setBinding('');selected.current='';setResults([]);setBindings(rows=>rows.filter(row=>row.id!==binding));setJobs([]);setNotice('Pairing revoked.');}})}>Revoke selected computer</button><button className={button} disabled={busy} onClick={()=>void action(async(signal,expected)=>{if(!window.confirm('Revoke all computer pairings belonging to your LearnBridge account? This also supports recovery after a lost local credential.'))return;await phoneRelay({operation:resultsEnabled?'recover':'revoke_all',results:resultsEnabled,body:{},signal});if(expected===epoch.current){invalidate();setBinding('');selected.current='';setBindings([]);setJobs([]);setResults([]);setNotice(resultsEnabled?'The relay acknowledged revocation and active response erasure.':'The relay acknowledged revocation of your computer pairings.');}})}>Recover account: revoke all pairings</button></div></section>
 </div>;
}
